### ISSUE TITLE
View details of one feed

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#1]
Here is the latest mockup for the screen showing the details of one feed (note that some cards in the pipelines on the bottom are minimized, some are maximized):

**Main feed details page**
![demo_feed-details_05b](https://user-images.githubusercontent.com/799683/52348746-135a7d80-29f3-11e9-87a8-e88daa62e3c7.png)

Some points:
* The main navigation mechanism within the page here is the graph. Click on a node, and actions related to that node appear in the right side panel, and metadata / output for the node appear in a large card below.
* Two special cases to the above - the root node in the graph will not have the 'share this pipeline' button, and neither will any leaf node in the graph.
* When "Add new node(s)" is hovered, a new node appears in the graph diagram on the left. It disappears when button focus is lost. 
* In the sidebar nav - this is under "my feeds". The previous screen is a listing of all feeds the user created (some marked private, some marked shared). The "feeds shared with me" is a listing of feeds created by other users that have been shared with the logged in user. "My Dashboard" isn't defined yet and may go away.

**Dialog: Run pipeline**

WIP

**Comment by jcaianirh** [comment]
@mairin i think this can be closed, if there are any missing details from this issue, could you pull them out and add a new issue. otherwise this one looks complete!
