### ISSUE TITLE
ChRIS UI: Create small React widget to display thumb for medical images, to be used in ChRIS UI file browser

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#100]
(@abdullahsikder)

**Comment by junaruga** [comment]
Could you explain more about this? What is ChRIS UI file browser?
What is a next action for this task?

**Comment by abdullahsikder** [comment]
Hi Jun, 

Sure. To explain the issue in a bit more detail, on the clicking Add New Feed and then proceeding onto uploading an image allows one or multiple images to be uploaded. Now when uploaded this only retrieved the string (name of file) to the front-end and displays that.

The task is to retrieve both the name of the upload file (string) and the image itself ( img src) to be able to display on that tab.

**Comment by junaruga** [comment]
Thanks for the explanation. Okay. In my understanding, this ticket is a feature to add the name of the uploaded image file from the web UI.

**Comment by DivyanshiSingh** [comment]
Is this issue open to work?
I would like to work on this. Please assign me this issue @mairin.

**Comment by DivyanshiSingh** [comment]
hello @mairin can you give the status of this issue. I would like to work on this.

**Comment by mairin** [comment]
Hey @DivyanshiSingh - lets wait until you've completed https://github.com/FNNDSC/ChRIS_store_ui/issues/102 - so other applicants have a shot. 👍

**Comment by yvan237** [comment]
Hey @DivyanshiSingh I am an outreach applicant, can I work on this issue?

**Comment by PintoGideon** [comment]
Steps to reproduce this issue:

1. Click on the 'create feed' button once you login.
![Step_1](https://user-images.githubusercontent.com/15992276/114469266-cd913500-9bba-11eb-903b-c6e7788777cf.png)

2. Provide a name to the feed and click 'next'.
![Step_2](https://user-images.githubusercontent.com/15992276/114469392-0f21e000-9bbb-11eb-8c62-058f1554c44c.png)

3. Choose the option 'Upload new files from your local computer'
![Step_3](https://user-images.githubusercontent.com/15992276/114469453-2f519f00-9bbb-11eb-87fd-79c9f99e225c.png)

4. Upload a local file from your computer. In this case, I choose a .png file.
![step_5](https://user-images.githubusercontent.com/15992276/114469504-4abcaa00-9bbb-11eb-87eb-9f16b4ce0518.png)
The UI currently just shows a string, the idea is to also display a thumbnail is possible.

**Comment by yvan237** [comment]
> Hi Jun,
> 
> Sure. To explain the issue in a bit more detail, on the clicking Add New Feed and then proceeding onto uploading an image allows one or multiple images to be uploaded. Now when uploaded this only retrieved the string (name of file) to the front-end and displays that.
> 
> The task is to retrieve both the name of the upload file (string) and the image itself ( img src) to be able to display on that tab.

From this explanation above, I understood the task is about getting the image that has been uploaded and displaying it alongside the name of the image in the UI [File attached below]. 
So I faced issues displaying the image blob after getting it from the server.


It seems I didn't understand properly.
<img width="731" alt="Screen Shot 2021-04-12 at 23 36 43" src="https://user-images.githubusercontent.com/72573500/114471097-f2e86800-9be7-11eb-99bd-6c3fb1602849.png">

**Comment by PintoGideon** [comment]
Oh, that feature already exists right ? If you click on the image, you should see a preview right ?

![Before](https://user-images.githubusercontent.com/15992276/114471711-10550c00-9bbf-11eb-88f8-b55d0ddd2cde.png)

**Comment by yvan237** [comment]
Yeah I can see the preview, I will move on with the correction.

Thanks a lot @PintoGideon

**Comment by PintoGideon** [comment]
No worries @yvan237 , Also, hold off on this issue. This is not fleshed out completely. I'll assign you with an alternate issue.

**Comment by mairin** [comment]
@PintoGideon FWIW, your comment here outlines the original intent of this bug perfectly:
https://github.com/FNNDSC/ChRIS_ui/issues/100#issuecomment-818279295
