### ISSUE TITLE
(Testing) Browser testing for COVID-Net frontend

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#102]
The COVID-Net UI works in Firefox and Chrome, but it is still typical for Internet Explorer to be in use at hospitals. We may want Microsoft Edge testing too. 

It would be very helpful to have an idea of how this UI performs in IE and to create issues found so we can get them fixed.

This is the repo for the COVID-Net UI:
https://github.com/darwinai/covidnet_ui

There is a readme file on the bottom of the front page of the repo that walks you through how to stand up the system.

Issues discovered can be filed here:
https://github.com/darwinai/covidnet_ui/issues

This repo will help you set up the UI with sample data:
https://github.com/darwinai/covidnet_integration

**Comment by junaruga** [comment]
Does anyone have Microsoft Edge on Windows environment?

Ref: Browser market share: https://gs.statcounter.com/browser-market-share

Can we use the this kind of tool ideally for free?
https://crossbrowsertesting.com/

**Comment by mairin** [comment]
@junaruga I do have a windows VM I can use for Microsoft Edge testing if need be. I wonder if the Red Hat web team has a cross browser testing tool we could get an account on.

**Comment by junaruga** [comment]
> I do have a windows VM I can use for Microsoft Edge testing if need be.

OK. Nice.

> I wonder if the Red Hat web team has a cross browser testing tool we could get an account on.

Hum.

**Comment by khushishikhu** [comment]
@mairin Hi, I am an outreachy applicant. May I work on this issue?

**Comment by mairin** [comment]
@khushishikhu sure, you can use https://covidnet.chrisproject.org/ for testing. you can dm me on matrix or slack for the password.

**Comment by mairin** [comment]
@khushishikhu Ah! Sorry about that it looks like we didn't have the sample data loaded in when you ran it. Can you try it again now that the sample data is loaded? Here's a testing script from our upcoming user testing that you could follow for running through it on your own:

1. Create new COVID-Net predictive analysis via patient MRN. Create one for each patient type (Normal, Pneumonia, and COVID-19) and make sure the system provides the correct analysis for the given patient (so the COVID-19 MRN results in a COVID-19 likely analysis outcome.)
2. Look up existing COVID-Net predictive analysis in the system (given patient MRN)3. 
3. Examine patient imaging and ensure it works as expected
4. Generate a PDF report of patient predictive analysis, and assess whether or not the output would be useful and its formatting is sensible.
5. Please jot down any bugs, errors, or doubts encountered while running through the above.

Here are the sample MRNs to use:

Diagnosis type | Anonymized token | Tasks
-- | -- | --
Normal | MRN DAI000290 | 1, 3
Pneumonia | MRN DAI000927 | 2, 3
COVID-19 | MRN DAI000322 | 3, 4

Do you know of any good browser testing platforms we could take a look at too instead of running manual testing? https://crossbrowsertesting.com/ is something Jun mentioned above but it's a subscription-based site. If there was an open source tool we could run or some kind of freeware tool it would be great. Is that something you could research?

**Comment by khushishikhu** [comment]
@mairin Sure I will try the testing again from the information you have provided me Thank you for that. 
No, I currently don't know any browser testing platform but I will research about is and will let you know what can be done according to my research. Also I have a doubt that here I have tested in Microsoft Edge but you have asked to do in Internet explorer which is for that I think we need to find anything like browser testing , because now a days many of us doesn't have Internet explorer in our laptops( even when I work on windows OS) . But I will research about how we can do this task so that we can test in IE too.

**Comment by AryaArunB** [comment]
@mairin I have created an account on https://crossbrowsertesting.com/ I am researching a bit. It would help me a ton if i could get the link to the hosted version of the webapp. thanks!

**Comment by AryaArunB** [comment]
I tried testing this on crossbrowsertesting.com. It's working on chrome but I'm afraid it's not working on internet explorer.
<img width="1440" alt="Screenshot 2022-04-18 at 12 56 00 PM" src="https://user-images.githubusercontent.com/60646682/163772434-3158aed2-c856-4092-a28b-b7f66586a561.png">
