### ISSUE TITLE
Feed Creation Notes

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#112]

**Comment by rudolphpienaar** [comment]
Steps should be:

1. Basic Information

2. Feed Data Source

2.1 If choose "Generate files from FS plugin", then:
2.1.1. Remove the "Data Packs" language and replace with "Feed Synthesis Plugin" with the sub heading "Please choose the Feed Synthesis Plugin you'd like to run"

2.2 For all the other choices that currently say "Data Configuration", replace that text with "File Selection"

**Comment by rudolphpienaar** [comment]
The file upload progress bar:

1. Should track with the number of files being uploaded.

Right now, about the first 25% of the progress immediately fills up, then all the pushing of files has no progress movement of files.

Have noticed that many times the progress bar goes RED even though the upload is successful.

**Comment by rudolphpienaar** [comment]
Have noticed that the RED progress bar seems to happen often with upload of MANY files.

**Comment by PintoGideon** [comment]
Issues found in the js clent and the server response.
1. The error caught in the UI from the client is 'No server response'.

2. [2020-10-13 12:32:58,949] [INFO][client 43 140036368480000] REQ: curl -i http://swift_service:8080/v1/AUTH_chris/users/chris/uploads/test-upload-75/0191-1.3.12.2.1107.5.2.19.45152.2013030808105486367685381.dcm -I -H "X-Auth-Token: AUTH_tk098e57be9..."
[2020-10-13 12:32:58,949] [INFO][client 43 140036368480000] RESP STATUS: 404 Not Found
[2020-10-13 12:32:58,949] [INFO][client 43 140036368480000] RESP HEADERS: {'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'X-Trans-Id': 'tx157a6b37863c4e7b9e375-005f85d6ba', 'X-Openstack-Request-Id': 'tx157a6b37863c4e7b9e375-005f85d6ba', 'Date': 'Tue, 13 Oct 2020 16:32:58 GMT'}


3. [2020-10-13 12:38:40,616] [WARNING][connectionpool 43 140036368480000] Connection pool is full, discarding connection: swift_service
