### ISSUE TITLE
Spinning wheel in output viewer fullscreen is not centered

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#128]

**Comment by Zoey-dev** [comment]
HI @rudolphpienaar  I am an outreachy intern, I would like to work on this issue. 
Could you please give me more details and assign this to me?

**Comment by PintoGideon** [comment]
Hi @Zoey-dev , This issue is now solved. We may have missed out on closing this.

**Comment by Zoey-dev** [comment]
Oh okay @PintoGideon.Thanks.  Can i work on issue #131 ?
