### ISSUE TITLE
"Create New Feed" file upload with upload selection -- icon and text are not centered in window

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#131]

**Comment by mairin** [comment]
@Zoey-dev is working on this one, but for some reason I am unable to assign it to her.

**Comment by Zoey-dev** [comment]
Hello, can i get a little more description on this?

**Comment by mairin** [comment]
@Zoey-dev it looks like this one somehow got fixed in the meanwhile (neither myself or Jennings could reproduce) so I am just going to close it out. Sorry for the confusion!

**Comment by Zoey-dev** [comment]
Its fine. Thanks
