### ISSUE TITLE
Background image at /login does not work in Firefox (works in Chrome/Chromium only)

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#166]

**Comment by somya51p** [comment]
@jennydaman I wish to work on this issue. I am an Outreachy applicant.

**Comment by jennydaman** [comment]
I found the problem.
https://github.com/FNNDSC/ChRIS_ui/blob/4c8564572be56c254abf0ce399f1d1a850618760/src/assets/scss/components/_background-image.scss#L22

It is a known issue that Firefox does not support `filter` in the same way the Chrome/Chromium does.
Well, this is a strange use anyway. It looks like @PintoGideon was playing with this, given there's a commented out line of code above. Is there a purpose to using `filter` here? We are setting the background using `background-image` anyways.

**Comment by jennydaman** [comment]
@somya51p you may wish to investigate this and consider some refactoring. Background image definition is all over the place

- `assets/scss/components/_background-image.scss`
- `pages/LogIn/login.scss`

My guess is that the purpose of `assets/scss/components/_background-image.scss` is to be generally useful anywhere we want to give a component a background image. In our [design mockups](https://github.com/FNNDSC/cube-design/blob/master/CHRIS-UI/feed-individual.svg), we see that the appbar has a background image.

**Comment by jennydaman** [comment]
Interesting observation! When I opened the link above to the design mockups, Github converts the SVG into PNG and displays that on the webpage. But opening the raw SVG in a new file, Firefox fails to show the background image for the appbar.

**Comment by somya51p** [comment]
@jennydaman I will go through it and try to resolve it as soon as possible. Thanks for the help.

**Comment by jennydaman** [comment]
@somya51p no rush! I think we should pause to think about what the best way to do things would be and try to keep our code clean. After all, part of why this but wasn't straightforward is because it was hard to find `assets/scss/components/_background-image.scss`. Aside from refactors, would you help us write some comments?

It might be a good idea to base your changes off of a fork of https://github.com/FNNDSC/ChRIS_ui/pull/221

**Comment by somya51p** [comment]
Yeah sure @jennydaman.
