### ISSUE TITLE
Add link to readme which gives a walkthrough to the project

### ISSUE THREAD

**Issue by Aaishpra** [FNNDSC/ChRIS_ui#204]
## Description
Add this **[link](http://chrisproject.org/join-us)** under the `resources` heading which gives a walkthrough about the project so that new contributors can know more about the project.

**Comment by PintoGideon** [comment]
Hey @Aaishpra , What do you think about adding that link under the 'Learn More' heading ? I think it fits there.

**Comment by Aaishpra** [comment]
Sure will place it there then.
