### ISSUE TITLE
Convert Class Components into Function Components.

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#206]
There a few class components that can be re-written into function components for a cleaner API.

List of the components that need to be re-written will be added here shortly.

**Comment by Deek9399** [comment]
Hello, I am an outreachy applicant. I would like to work on this issue.

**Comment by PintoGideon** [comment]
Hey @Deek9399 , Welcome to the project.

If you navigate from the root folder to the layout folder (src/containers/Layout), you will see a few components that need to be rewritten using hooks for a cleaner api. 
```
Header.tsx
PageWrapper.tsx
Sidebar.tsx
Toolbar.tsx
```

Let me know if you would like to take that up as a task and I'll assign this issue to you. Feel free to ask me any questions.

**Comment by somya51p** [comment]
@PintoGideon If this issue is not assigned to @Deek9399, I wish to work on the same.

**Comment by Deek9399** [comment]
@PintoGideon You can assign this issue to @somya51p. I am getting myself familiar with the project. If the issue is still available, I will check back again.

**Comment by PintoGideon** [comment]
Hi @somya51p , This issue is now assigned to you. Feel free to reach out with any questions.

**Comment by somya51p** [comment]
Yeah sure, ThankYou!

**Comment by Aaishpra** [comment]
Hey, @jennydaman @PintoGideon I see no updates, can I take this up?

**Comment by PintoGideon** [comment]
Hey @somya51p , Any update on this ?

**Comment by somya51p** [comment]
@somya51p I had started working, just need some time.

**Comment by PintoGideon** [comment]
No worries @somya51p
