### ISSUE TITLE
Responsive Design for the Dicom Viewer.

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#207]
The set of Tools need to be centered in the screen for smaller screen sizes.

**Ideal:**

![Tools need to be centered](https://user-images.githubusercontent.com/15992276/113199692-6af07e80-9235-11eb-8f48-788882bf186e.png)

**Current:**

![Unresponsive_Design](https://user-images.githubusercontent.com/15992276/113199672-662bca80-9235-11eb-8a72-9d72746e948c.png)

**Comment by Zoey-dev** [comment]
Or @PintoGideon this issue?

**Comment by Zoey-dev** [comment]
Thank you

**Comment by Zoey-dev** [comment]
@PintoGideon can i create a new branch for this?

**Comment by jennydaman** [comment]
You should create a fork of the repository and then create a branch off of your fork. Let me know if you need help.

**Comment by Zoey-dev** [comment]
> You should create a fork of the repository and then create a branch off of your fork. Let me know if you need help.

Okay @jennydaman thank you.

**Comment by Zoey-dev** [comment]
@jennydaman i have done the forking and cloned my fork and then i updated the env file and input the link that points to the api but then node_modules are missing and its causing errors in the component. i ran npm install and there were errors

**Comment by Zoey-dev** [comment]
> @jennydaman i have done the forking and cloned my fork and then i updated the env file and input the link that points to the api but then node_modules are missing and its causing errors in the component. i ran npm install and there were errors

this is the error i keep getting when i run npm install.: 

npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN rc-picker@2.5.10 requires a peer of dayjs@^1.8.30 but none is installed. You must install peer dependencies yourself.
npm WARN react-cornerstone-viewport@4.0.5 requires a peer of cornerstone-wado-image-loader@3.0.x but none is installed. You must install peer dependencies yourself.

audited 2572 packages in 38.275s

164 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by PintoGideon** [comment]
Hey @Zoey-dev , What version of node are you using ? Also, could you please send me a screenshot of the errors you are seeing?

**Comment by PintoGideon** [comment]
Ohh @Zoey-dev , those are just npm warnings.The UI should instantiate in your browser at the port 3000.

**Comment by Zoey-dev** [comment]
> Hey @Zoey-dev , What version of node are you using ? Also, could you please send me a screenshot of the errors you are seeing?

my version is v14.16.0

**Comment by Zoey-dev** [comment]
> Ohh @Zoey-dev , those are just npm warnings.The UI should instantiate in your browser at the port 3000.

okay so i should just run npm start and ignore them.? my node_modules are still not showing

**Comment by PintoGideon** [comment]
Looks good to me @Zoey-dev . Do you see this screen ?

![Successful_Instantiation](https://user-images.githubusercontent.com/15992276/113741473-affe3000-96cf-11eb-93b0-d15457d1a4d7.png)

**Comment by PintoGideon** [comment]
Yes @Zoey-dev . Run `npm start`.

**Comment by Zoey-dev** [comment]
> Looks good to me @Zoey-dev . Do you see this screen after running `npm start `?
> 
> ![Successful_Instantiation](https://user-images.githubusercontent.com/15992276/113741473-affe3000-96cf-11eb-93b0-d15457d1a4d7.png)

it is still starting the development server, haven't seen this yet

**Comment by Zoey-dev** [comment]
yayyyy, it compiled successfully

**Comment by PintoGideon** [comment]
Good job persisting with this and making it work for you. @Zoey-dev

**Comment by Zoey-dev** [comment]
Thank you. Is it okay to reach out if i have other challenges?

**Comment by PintoGideon** [comment]
Yes @Zoey-dev , Let me know if you run into issues,

**Comment by Zoey-dev** [comment]
> Yes @Zoey-dev , Let me know if you run into issues.

🙈  I can't find this page. How do i navigate to the page so i can see if the changes i made are working. I mean the "ChRIS Output Viewer" page

**Comment by jennydaman** [comment]
@Zoey-dev you need to create a feed with some data. Are you using `cube.outreachy.chrisproject.org` or a locally running backend?

One way to get some data would be to run FS plugins. For example, [pl-mri_sag_anon_192](https://chrisstore.co/plugin/35)

**Comment by Zoey-dev** [comment]
> @Zoey-dev you need to create a feed with some data. Are you using `cube.outreachy.chrisproject.org` or a locally running backend?
> 
> One way to get some data would be to run FS plugins. For example, [pl-mri_sag_anon_192](https://chrisstore.co/plugin/35)
> 
> After you have some data to look at, you can navigate to the output viewer.


I have "https://cube.outreachy.chrisproject.org/api/v1/" in my .env file pointing to the api.

**Comment by jennydaman** [comment]
I've installed the plugin `pl-mri_sag_anon_192` on that backend already. Please try running it.

**Comment by Zoey-dev** [comment]
There are about 5 feeds being displayed.

**Comment by jennydaman** [comment]
@Zoey-dev I take that as a good thing?

**Comment by Zoey-dev** [comment]
> @Zoey-dev I take that as a good thing?
> 

Yes it is. Thanks

**Comment by Zoey-dev** [comment]
@PintoGideon please could you review the PR and let me know if there are more things i should work on

**Comment by PintoGideon** [comment]
Hey @zoey-dev, Sure. I can think of a few issues that need to be tackled. I'll add them tomorrow and feel free to pick one of those up. I'll review your PR in the meanwhile.

Good job in getting this all figured out.

**Comment by Zoey-dev** [comment]
> Hey @Zoey-dev, Sure. I can think of a few issues that need to be tackled. I'll add them tomorrow and feel free to pick one of those up. I'll review your PR in the meanwhile.
> 
> Good job in getting this all figured out.

Thank you very much

**Comment by jennydaman** [comment]
@PintoGideon what changes have you made in the past week? The "Current" screenshot in the first comment of this issue is not accurate to the 2021-04-06 update.

![comfortable screenshot](https://user-images.githubusercontent.com/20404439/113945301-140a1c80-97d4-11eb-9dd1-c28f45adee7a.png)

![narrow screenshot](https://user-images.githubusercontent.com/20404439/113945339-26845600-97d4-11eb-859a-878242669cd9.png)

**Comment by PintoGideon** [comment]
Hey @jennydaman , I was working on this issue originally before it was assigned to @Zoey-dev . I made a few edits to the layout of the tools, but did not add media queries. It was then assigned to @Zoey-dev .
