### ISSUE TITLE
Show spinner before list of feeds is loaded

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#209]

**Comment by roshnaeem** [comment]
Hello @jennydaman! can you please provide a little detail. I want to work on this issue.

**Comment by jennydaman** [comment]
After logging in (username: chris, password: chris1234) and going to https://app.chrisproject.org/feeds
you see "No feeds found" for a split second before the feeds show up.

It'd be nicer if the "No feeds found" page was a loading spinner instead, and so "No feeds found" is shown only when the response resolves and the data is empty.

**Comment by roshnaeem** [comment]
@jennydaman, please assign me this issue!!

**Comment by PintoGideon** [comment]
@roshnaeem , This task is assigned to you now. Let me know if you have any questions.

**Comment by PintoGideon** [comment]
Hi @roshnaeem , were you able to setup the UI on your system? Any update on this issue?

**Comment by roshnaeem** [comment]
Hello @PintoGideon , yes I have set up the UI, I'll start working on it on weekend.

**Comment by PintoGideon** [comment]
Sounds great @roshnaeem

**Comment by zrthxn** [comment]
@PintoGideon I think this is a pretty simple fix, is it okay if I complete this right now? Asking since you've assigned it.
