### ISSUE TITLE
Test Error: syntax error using inital state in the message reducer tests

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_ui#22]
@xhyzzZ could you fix this. fetch the upstream master, and then rebase your code and run npm test to reproduce.

**Comment by xhyzzZ** [comment]
I think it was wrong because there is no typescript syntax recogizer in package.json file, cuz i can't run npm test in my local environment too. But i can run on my former ChRIS which i write these lines：


`module.exports = {
    // look for ts files
    testMatch: ["**/*.test.(j|t)s?(x)"],
    // tells it that ts/tsx files are valid modules
    moduleFileExtensions: ["js", "json", "jsx", "node", "ts", "tsx"],
    // explicitly transform ts/tsx with babel
    transform: {
        "^.+\\.tsx?$": "babel-jest",
    },
}`

**Comment by jcaianirh** [comment]
@xhyzzZ: The only issue is: 
Expected value to equal:
      {"initialState": {"confirmation": {"confirm": {"action": "do", "data": "anytype", "label": "cat"}, "dismiss": {"action": "doit", "data": "anytype", "label": "dog"}, "text": "hi", "title": "world"}, "message": {"displayType": "modal", "message": "hello", "type": "success"}}}
    Received:
      {"confirmation": {"confirm": {"action": "do", "data": "anytype", "label": "cat"}, "dismiss": {"action": "doit", "data": "anytype", "label": "dog"}, "text": "hi", "title": "world"}, "message": {"displayType": "modal", "message": "hello", "type": "success"}}

**Comment by jcaianirh** [comment]
The error you received above is because you may not have fetched the latest code from the repo.
