### ISSUE TITLE
Update background graphic for ChRIS UI login screen

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#220]
This ticket involves updating the background on this screen:
![Screenshot from 2021-04-08 12-03-45](https://user-images.githubusercontent.com/799683/114059573-7f9acb00-9862-11eb-88e4-b26e678bf884.png)

Fixing this issue will include the following tasks:
- [ ] Use optipng or a similar tool to optimize the background graphic (attached below)
- [ ] Create scaled versions of the graphic for the various sizes used by pattern fly. The attached graphic below is the same dimensions as the default largest size.
- [ ] Update the background of the ChRIS UI login screen with the image, such that the correct size of the image loads responsively

![bkgd-chris-nodes](https://user-images.githubusercontent.com/799683/114059468-65f98380-9862-11eb-83b2-4f284a021350.png)

Please feel free to ask any questions / doubts you might have on this task. Cheers!

**Comment by zrthxn** [comment]
@mairin I'd like to work on this if that's alright.

**Comment by mairin** [comment]
@zrthxn Sure thing!

**Comment by zrthxn** [comment]
Just one question, do you think it's necessary in this case to optimize the graphic? Because the total size of all the image files (for all sizes) is currently coming out to be about equal to that of the largest one we had previously (x2000). So the load time gained by optimization would be very small.

**Comment by mairin** [comment]
@zrthxn Yep I do! It doesnt hurt at all and takes like 10-15 min unattended.
