### ISSUE TITLE
"Latest news" or welcome screen

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#223]
Currently, the home page is mostly empty with one box that just says

> Info alert:Welcome to the ChRIS UI Dashboard

It can be populated to feature recent news, perhaps similar in design to a newspaper cover. For example, it can feature the latest plugins which have been uploaded to ChRIS_store, or discuss our collaborations and partnerships (Outreachy, Mass Open Cloud).

**Comment by Aaishpra** [comment]
Hey @jennydaman can i take this up?

**Comment by jennydaman** [comment]
Sure.

This was an idea that has been floating in my head for a little while but haven't had time to do it. As with anything related to UX design, ideas should be run by @mairin first. Mairin, what do you think about it? Maybe like what this website has (scroll down past the birthday announcement, to the cards about news, events, ...) https://galaxyproject.org/

@Aaishpra I leave the responsibility of creativity up to you. Ideally, it would be implemented in a way that is easy to customize — in the deployment of ChRIS internal to the Boston Children's Hospital, I'd like to have it show off things relevant to its use: link to documentation, new plugins available, maybe a dynamic widget such as cluster load average...

For an introductory Outreachy task, I'd suggest you start small, some static text would be nice. Here are some ideas for content, pick a subset of anything or think of new things.

# Ideas

- a link to https://chrisproject.org/docs
- statuses from https://lists.chrisproject.org/
- some news: an Outreachy shoutout
- something random, like [fortune-mod](https://en.wikipedia.org/wiki/Fortune_(Unix))
- tips and tricks
  - how to search for plugins: `https chrisstore.co/api/v1/plugins/search/ name_exact==pl-fetal-brain-mask accept:application/json | jq -r '.results[] | .name + " " + .version + " " + .url'`
  - did-you-knows, singularity vs docker
- recent development
  - NIFTI file supported in UI https://github.com/FNNDSC/ChRIS_ui/pull/193
  - file size supported by backend API https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/310
  - COVIDNet is cool, https://covidnet.chrisproject.org/

Forgive my narcissism, but some good content could be about the things I'm doing:

- recently developed plugins (I'm linking to chrisstore.co just cause, but the details are at their Github READMEs because chrisstore.co is not functional)
  - [pl-fetal-brain-mask](https://chrisstore.co/plugin/71)
  - [pl-fetal-brain-assessment](https://chrisstore.co/plugin/72)
  - [pl-ANTs_N4BiasFieldCorrection](https://chrisstore.co/plugin/77)
  - [pl-infantfs](https://github.com/FNNDSC/pl-infantfs) (no chrisstore.co link because this is not free software)

I'm giving a talk on April 30 at 10:00
"Fetal Brain MRI Pipelines on ChRIS: Accessibility and Reproducibility of Medical Compute on the Open Cloud"
https://bostonchildrens.zoom.us/j/96332877103?pwd=TEhCN2lKZ2tod1NpSnlrYnJlSEdqQT09
Meeting ID: 963 3287 7103
Password: 392957

**Comment by Aaishpra** [comment]
Thank you so much for adding these @jennydaman I was thinking to ask for more details for the content part of the homepage.
So I had a look at the Homepage and I guess I would like to remove that info alert "Welcome to the ChRIS UI Dashboard" from there instead add a bold Heading in the place. After that can we give a little bit of introduction about what ChRis UI is and its features, not much just a paragraph, then we can definitely add those cards and different kinda information in them. At the end of the page, we can add all important links to the docs/Github and other links you can suggest (maybe contact or some gmail).

>I'm giving a talk on April 30 at 10:00
"Fetal Brain MRI Pipelines on ChRIS: Accessibility and Reproducibility of Medical Compute on the Open Cloud"
https://bostonchildrens.zoom.us/j/96332877103?pwd=TEhCN2lKZ2tod1NpSnlrYnJlSEdqQT09
Meeting ID: 963 3287 7103
Password: 392957

I would definitely join the talk if I can (although don't have much knowledge about medical sciences and tools but would like to know more about it for the project)

**Comment by jennydaman** [comment]
The design here seems delicate, I think it will be important to avoid clutter (my example at https://galaxyproject.org is cluttered, it's just an example of what I mean and not an example to copy or get inspired by) and try to keep an inviting tone.

An introduction to ChRIS_ui would be great. Here's some content ideas:

- Just visiting? Try the demo user account `chris:chris1234`
- Get started by clicking on "Feeds List"
- NEW! NITFI files are now supported in the integrated viewer.

btw about my talk: the audience will be very diverse: clinicians, researchers, biologists, software devs. It'll be a challenge for me to present the information in such a way to appeal to all backgrounds. With that said, I won't be going in depth into advanced medical biology.

**Comment by Hina-softwareEngineer** [comment]
Hello everyone, 
I want to contribute to this codebase. I am new to this. Can I work on this issue? or  Do you have any idea regarding design of dashboard? You can share.

**Comment by ankittt20** [comment]
Hey @jennydaman can i work on this?

**Comment by jennydaman** [comment]
This issue has been resolved, though #300 needs to be worked on
