### ISSUE TITLE
A few improvements in the documentation structure

### ISSUE THREAD

**Issue by archanaserver** [FNNDSC/ChRIS_ui#224]
**Current Structure:**
The documentation is good and clean. It's showing that we can setup this project locally by following few steps but that is bit confusing.

**What improvement this need?**
So, I want to make few things clear that, while starting UI development if we can add the alternative method too- like using `node/yarn` or you can do this setup using `docker` too.

**Comment by archanaserver** [comment]
Hi @jennydaman can you please assign in with this issue? I want to work on that.

**Comment by jennydaman** [comment]
Sure.

I suggest that you include a link to [miniChRIS](https://github.com/FNNDSC/miniChRIS) as it is easier than the current documentation on how to start the backend for development purposes.

**Comment by archanaserver** [comment]
Yes sure! I got it, i'm working on it. 👩🏻‍💻
