### ISSUE TITLE
Post-login destination

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#225]
Let's say I click on the URL

https://app.chrisproject.org/feeds/3

It's going to redirect me first to https://app.chrisproject.org/login
After logging in, I am taken back to the home page instead of `/feeds/3`

The proposal is to implement a redirect to some login page with a query string like

```
https://app.chrisproject.org/login?next=/feeds/3
```

And then after logging in, automatically navigates to desired page.

**Comment by archanaserver** [comment]
I got it, can I work on this issue @jennydaman ?

**Comment by janvi01** [comment]
Hey, @jennydaman is this issue still available?

**Comment by jennydaman** [comment]
@janvi01 This feature is done, thanks for asking.
