### ISSUE TITLE
Show Password functionality in login page

### ISSUE THREAD

**Issue by somya51p** [FNNDSC/ChRIS_ui#230]
The signup page has the functionality of show passwords, what if the login page also has this functionality. I wish to work on this issue. Please go through it. @jennydaman @PintoGideon

**Comment by jennydaman** [comment]
Have at it.

I would consider using an icon, right-aligned in the box, and maybe show the password only as the button is being held down (hiding on mouseUp).

**Comment by zrthxn** [comment]
@jennydaman Patternfly already has this functionality built-in. Its only an attribute to add in the LoginForm component. It'll probably be add in the fix for #221 in which I'm fixing the login page layout.
