### ISSUE TITLE
Docker entrypoint to overwrite REACT_APP_CHRIS_UI_URL in docker image

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#231]
The ChRIS_ui takes a long time to build, so using the build off of DockerHub is faster. However, `REACT_APP_CHRIS_UI_URL=localhost:3000` is compiled into the static `build/` files.

For convenience, we could provide a `docker-entrypoint.sh` as `ENTRYPOINT` which uses `sed` (or the like) to overwrite in the static `build/` dir the backend's URL with something given at runtime. e.g.

```bash
docker run --rm -p 3000:3000 -e REACT_APP_CHRIS_UI_URL=http://localhost:12345/api/v1/ fnndsc/chris_ui:latest
```

**Comment by mocktarissa** [comment]
Hello @jennydaman I'm an Outreachy Applicant can I have a go with this?

**Comment by jennydaman** [comment]
@mocktarissa Absolutely.

It's either a quick fix, or a good chance to learn Linux and Docker. hmu on slack if you need help.

**Comment by mocktarissa** [comment]
OK, i will get on it.
