### ISSUE TITLE
Stack scroll disclaimer in the preview screen for nifti files.

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#243]
Hey @jennydaman ,

For nifti files, you can use a mouse scroll to view the images in the stack. It may not be too obvious for a user so we could add a small text mentioning that. Let me know what you think.

![Stack_Scroll](https://user-images.githubusercontent.com/15992276/115046245-3fac9700-9ea5-11eb-8abc-2f2af147ffda.png)

**Comment by rudolphpienaar** [comment]
Just be aware that not all nifti files are stacks/volumes so adding text based only on filetype could have unintended consequences. I'm inclined to think a bit that the scroll bar hint as well as the text in the bottom left of `1/288` are sufficient. But I'm operating from the experience that nii files can be vols.

I might suggest that a maybe a mouse-over hint for the case where there is a scollable stack might work? Something like "Use scrollwheel to move through stack" in the case where there is a stack?
