### ISSUE TITLE
Pipeline browser

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#268]
Create a new tab in the ChRIS_ui which shows a list of existing pipelines in ChRIS.

The view should render pipeline tree structure previews.

https://github.com/FNNDSC/cube-design/blob/master/CHRIS-UI/Pipeline724.svg
https://github.com/FNNDSC/cube-design/blob/master/CHRIS-UI/pipeline-list_mobile.svg
https://github.com/FNNDSC/cube-design/blob/master/CHRIS-UI/individual_pipeline_details718-pipeline_activity.PNG

**Comment by mightyFZeus** [comment]
@jennydaman i would like to resolve this issue...kindly assign to me

**Comment by jennydaman** [comment]
This feature has been implemented already, thanks for helping to identify a stale issue.
