### ISSUE TITLE
Prevent app crashes on ChRIS API error

### ISSUE THREAD

**Issue by zrthxn** [FNNDSC/ChRIS_ui#273]
The application crashes while browsing the file tree in the feed creation wizard. Theres no problem in the app itself but if the API returns anything other than status 200, or throws an error the app will crash.

>  Error while fetching feed files o: Internal server error

![Screenshot from 2021-06-29 12-34-51](https://user-images.githubusercontent.com/35369637/123752762-c1be3080-d8d6-11eb-9047-c429e3b590e7.png)

### Expected Behavior 
The error should be handled and some sort of notification shown.

**Comment by zrthxn** [comment]
In both of these examples, I think catching the error just to re-throw it, isnt a good idea if there isnt any error handling in the calling function. Maybe these catches can instead trigger some sort of notification, like in the Store UI.

https://github.com/FNNDSC/ChRIS_ui/blob/a8e39baec89b538588a0e5f50fc95a31b6934a60/src/components/feed/CreateFeed/utils/fileSelect.ts#L169-L173

https://github.com/FNNDSC/ChRIS_ui/blob/a8e39baec89b538588a0e5f50fc95a31b6934a60/src/components/feed/CreateFeed/utils/fileSelect.ts#L176-L191

**Comment by PintoGideon** [comment]
Hey @zrthxn , thanks for creating the issue.

Could you please list down your workflow so I can reproduce this on my end?

**Comment by zrthxn** [comment]
@PintoGideon 

- opened the feed creation wizard
- entered name and selected type "choose data already registered to ChRIS"
- open "user" folder in tree browser
- open "feed8" folder under user "Chris"
- app crashes

**Comment by PintoGideon** [comment]
I'll work on a notification mechanism for these errors. Thanks for reporting this @zrthxn
