### ISSUE TITLE
Welcome tour, tutorial video, or getting started guide

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#300]
There should be some kind of introductory material presented to the user to explain basic concepts (feed, plugin, file) and the UI layout (sidebar, library, feeds list) e.g.

## Welcome Tour

A modal (pop-up), very common on popular web apps, should be shown once when a new user logs in.

A "tour" feature (which highlights components of the UI, showing a modal explaining the component) would be more effort but also more intuitive.

## Tutorial Video

Narrated or subtitled video of a user logging in, uploading data, and running a DS plugin. This video can be embedded on the main page, e.g. https://brainlife.io/

## Getting Started Guide

Just a plain help document which serves as a user introduction to ChRIS. Should include screenshots. e.g. https://guides.github.com/activities/hello-world/

**Comment by jennydaman** [comment]
https://chrisproject.org/for-users

**Comment by jennydaman** [comment]
A better idea than #223

**Comment by mairin** [comment]
Glossary of terms for creating this:

- feed
- plugin
- workflow
- pipeline
- app (like covidnet)

**Comment by mairin** [comment]
The help needed here for good first issue would be working on a way to present these concepts inside the ChRIS UI

**Comment by jennydaman** [comment]
Advanced implementation would use "feature discovery" feature, e.g. https://materializecss.com/feature-discovery.html (is there a Patternfly-compliant version of this?)

**Comment by OladapoAjala** [comment]
Hello @jennydaman @mairin can I be assigned this task?

**Comment by anayo-hub** [comment]
please can I be assigned to this issues!

**Comment by ShivraniAJ** [comment]
HI, I am Shivrani, I am selected as outreachy initial applicant, Please can you assign this issue to me?

**Comment by saabirin** [comment]
Hello l'am I am selected as outreachy initial applicant, Please can you assign this issue to me?

**Comment by imranburki** [comment]
I would love to contribute to this issue, if you please assign it to me.

**Comment by rudolphpienaar** [comment]
Dear @imranburki  @saabirin @ShivraniAJ @anayo-hub --

This "issue" concerns building the welcome tour, a video about ChRIS, how to use and setup etc. It is probably not ideal for someone who is not familiar with the system and has never started it or worked with it.

While I welcome contributions to this, can each of you please explain why you think you can contribute to this?

Best

**Comment by ShivraniAJ** [comment]
Yes, I am not familiar with the system right now, But I can definitely try 

> Dear @imranburki @saabirin @ShivraniAJ @anayo-hub --
> 
> This "issue" concerns building the welcome tour, a video about ChRIS, how to use and setup etc. It is probably not ideal for someone who is not familiar with the system and has never started it or worked with it.
> 
> While I welcome contributions to this, can each of you please explain why you think you can contribute to this?
> 
> Best

Yes, I am not familiar with the system right now, but I will try my best to get familiar with it as soon as possible and would like to collaborate with others on this issue.

**Comment by urviigupta** [comment]
@jennydaman @mairin Can I contribute to this issue?

**Comment by jennydaman** [comment]
@anayo-hub you are being assigned as per "first conme, first serve." As @rudolphpienaar mentioned, this issue is a big one and will require a high-degree of involvement --- you'll probably want to work close with me on it and do brainstorming/pair programming together.

@anayo-hub, would you be willing to collaborate with any of @ShivraniAJ, @saabirin, or @imranburki? I think it's good to work together with a partner (though more than 2 would incur inefficiencies).

**Comment by jennydaman** [comment]
@Dev-Comfie This issue is pretty old, I think it predates the population of the "Overview" tab with its current filler content. @mairin and I will be working on an "intro video," and once we have that out and uploaded to YouTube, I will create an issue for that intro video to be embedded in the Overview tab.
