### ISSUE TITLE
Use Github Actions to automatically build Container Images

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#304]
DockerHub autobuild is no longer part of their free tier.

Many of our other repositories are tested and built in Github Actions.

- https://github.com/FNNDSC/pfcon/blob/master/.github/workflows/ci.yml
- https://github.com/FNNDSC/pman/blob/master/.github/workflows/ci.yml
- https://github.com/FNNDSC/caw/blob/main/.github/workflows/container.yml

Use these examples to implement automatic container builds on GIthub Actions. The image should be pushed to the `docker.io` container registry and optionally `ghcr.io`.

Somewhat related helpful information here: https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds

**Comment by EUGINELETHAL** [comment]
@jennydaman can I take up this?

**Comment by EUGINELETHAL** [comment]
@zrthxn am not sure but looks like this issue was worked on by @Sandip117 on this commit https://github.com/FNNDSC/ChRIS_ui/commit/8590fac45cea3b4ae4f14dfae6c721c57f33bcae

**Comment by zrthxn** [comment]
@EUGINELETHAL yes it was.
