### ISSUE TITLE
Implement scale nodes via output size

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#307]
Right now if you view an analysis, you can click on the "Scale nodes on" switch in the upper left quadrant. Right now it provides a dropdown to let you switch between scaling the node size by "compute time"or "output size." Compute time is implemented, but output size is not yet implemented.

**Comment by ppk-1996** [comment]
I made the PR regarding to this issue. However, I am not sure what output size really means so I put the number_of_workers from the data. Please let me know any changes require.

**Comment by EUGINELETHAL** [comment]
@mairin can you assign to work on this issue?

**Comment by anayo-hub** [comment]
please @mairin I would love to contribute to this issue if assigned to

**Comment by somya51p** [comment]
@mairin @PintoGideon can I work on this issue. Please assign me the same

**Comment by jennydaman** [comment]
@anayo-hub a second apology from me for missing your comment. Though, you are already assigned to #300. How is work going with that? Message me on Matrix if you'd like to chat about these issues...

@somya51p this is partially implemented, however the node size of descendant plugin instances is scaled by the cummulative value of total compute time of itself and its parents, which is not what we want. This could be due to a backend limitation. I'll assign this issue to you, please let me know via Matrix if you want help with it.

**Comment by somya51p** [comment]
@jennydaman Surely, I will have a look into it and let you know the same. Thank you

**Comment by somya51p** [comment]
@mairin @jennydaman  What actually is output size referred to as over here. Is it the filesize as you have mentioned here [https://github.com/FNNDSC/ChRIS_ui/pull/313#issuecomment-946793542](url)

**Comment by codeEmpress1** [comment]
Hi @somya51p, I will like to know if you're still working on this. If yes, can I collaborate with you? If no @jennydaman, can you please assign it to me? Thank you.

**Comment by jennydaman** [comment]
@codeEmpress1 at your request I have assigned you to  https://github.com/FNNDSC/ChRIS_ui/issues/563, so I will leave this issue unassigned for now.

**Comment by oryxwhite** [comment]
Hi @jennydaman, I'm from Outreachy and I'm interested in working on this if no one else is assigned right now.

**Comment by oryxwhite** [comment]
@PintoGideon I've been working on a PR for this issue - was someone else able to fix it?

**Comment by PintoGideon** [comment]
@oryxwhite  Sorry, I wasn't aware of that. Is this an active PR ?

**Comment by oryxwhite** [comment]
@PintoGideon the last PR submitted was closed, I've been working on a new one to submit

**Comment by oryxwhite** [comment]
@PintoGideon @jennydaman I've submitted a PR for this, would you mind reviewing it?
