### ISSUE TITLE
Move "switch layout" button in analysis details screen

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#309]
the analysis details page has a "Switch Layout" button in the upper right panel. This button makes more sense in the graph view panel in the upper left panel. It would be good to move this button from the upper right to the upper left panel (for example see https://app.chrisproject.org/feeds/1485)

**Comment by Akpjunior94** [comment]
Thanks

**Comment by janvi01** [comment]
Is this issue still available?

**Comment by mairin** [comment]
![Screenshot from 2022-02-16 16-33-46](https://user-images.githubusercontent.com/799683/154361142-7b33de79-bf83-4586-8e7e-36c9a7ac301e.png)
 in case it is helpful, this is a screenshot showing what needs to be done to complete this ticket!

**Comment by mairin** [comment]
@PintoGideon is this one fixed? I still see it on app.chrisproject.org?

**Comment by janvi01** [comment]
Hey @mairin I am not able to set up chris locally to work on this issue.
Please guide me. Thanks!

**Comment by yaya-usman** [comment]
@mairin I'll like to be assigned this issue, if @Akpjunior94 no more working on it

**Comment by urviigupta** [comment]
Is this issue still available? I'd like to work on it @mairin

**Comment by jennydaman** [comment]
@yaya-usman, @urviigupta, please ping me on Matrix if nobody is responding to your comments on Github.

This issue is open, and I will assign @yaya-usman to it. Yaya, if you would like to accept @urviigupta's help and collaborate on this issue, it would be to the both of your advantages.

Besides just moving the button, it should probably be styled differently. This is discussed a little in #312 : perhaps the label should say "3D Layout" and be a toggle switch instead?

**Comment by urviigupta** [comment]
@yaya-usman do let me know if we can collaborate on this issue!

Thanks @jennydaman

**Comment by yaya-usman** [comment]
Thanks @jennydaman please kindly assign @urviigupta the issue, i am working on other project.  @urviigupta if you need any support, i'll be willing to offer help.

**Comment by urviigupta** [comment]
Thanks @yaya-usman I will reach out for help if required.
Kindly assign the issue to me @jennydaman

**Comment by ciradu2204** [comment]
@urviigupta, are you still working on this issue? If not, @jennydaman, can I work on it?

**Comment by jennydaman** [comment]
@urviigupta pair programming is encouraged but if you would rather work independently that is acceptable.

@ciradu2204 if you would like to meet with me one-on-one for help getting started with contributions, message me on Matrix.
