### ISSUE TITLE
Extend PACS lookup with Study/Series Description filters

### ISSUE THREAD

**Issue by EUGINELETHAL** [FNNDSC/ChRIS_ui#319]
Improve PACSLookUP  to  enable  searching by study descriprion and by FileNME

**Comment by bolajahmad** [comment]
is this an issue we're working on? did you complete the issue yet, to filter the data on the frontend. 
i would like to check this out, if you're working on it @EUGINELETHAL . i'll assume it's  still open with no replies.

**Comment by EUGINELETHAL** [comment]
@boljahamad, yah  I am still working on it.  I will update you on the
progress

**Comment by Quintinus98** [comment]
Hello @jennydaman is this issue still open, can I work on it?
@EUGINELETHAL did you complete this issue?

**Comment by jennydaman** [comment]
@Quintinus98 as mentioned in https://github.com/FNNDSC/ChRIS_ui/issues/319#issuecomment-949352176 currently `/api/v1/pacsfiles/search/` does not support partial match on the fields `StudyDescription` and `SeriesDescription`.

Maybe we should add that as a backend feature first? https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/444
