### ISSUE TITLE
(CHRIS UI - P1 - DESIGN) Add a node to a feed

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#33]
**Right now there isn't a UI-based way to add a new node to a feed. We need a design & front end implementation for this.**

# Some notes / considerations:

## What model do we want to be using for Feeds? 

The model we use matters, because it has implications for how the "Add node" functionality will work.

- **Instant Apply:** Right now the model is, as soon as a plugin is added to a feed it begins processing - so it's an 'instant apply' model. 
  - Instant apply is nice in that you don't have to worry about the feed details page being in a "mode" or "state" which can cause confusion for users if it's not super clear what the current state is. 
  - If the user makes a mistake that is then instant applied, recovery is difficult - right now it's tricky to implement (for example) canceling a plugin that is currently processing. 
  - There could also be an opportunity to overload the system by making a lot of mistakes and spinning up a bunch of plugins by hitting the wrong button multiple times. This could be prevented in the front end maybe through some kind of rate-limiting thing.

- **Compose & Play:** An alternative model would be a "compose & play" model, where there is a compose or edit mode where you build out your tree, then a "play" mode where you can run it. 
  - Compose & play modes introduce a concept of 'mode' which can cause confusion
  - Compose & play enables experimentation and is forgiving of mistakes - you can add / remove / configure nodes at will while in compose mode and not worry about correcting mistakes and without requiring complex functionality to cancel a running operation, and once satisfied with the entire composition can go into play mode and run the node tree.

## For MVP, will we allow adding both plugins and pipelines at a new node?

**For MVP we will only allow adding plugins**, but the design should support adding both eventually.

## Handling parameters when adding a node

When adding a plugin or pipeline, parameters may need to be set by the user. Pipelines have default values established for each parameter - plugins don't necessarily have default values for each parameter, and some parameters are required. 

We might want to consider presenting the parameters in this order of priority:
- Non-optional / Required parameters with no default values
- Optional parameters with no default values
- Non-optional / Required parameters with default values
- Optional parameters with default values

Here is an example parameter, showing fields from a parameter for the PACSpull plugin:
    - `{
         "optional": true,
         "type": "str",
         "default": "",
         "action": "store",
         "flag": "--PatientID",
         "name": "str_patientID",
         "help": "The PatientID to query."
      }`

## User workflow for adding a node to a feed

**This assumes the instant apply model, which is currently how cube works.** If we adopted a compose & play model, only workflow steps 1-5 would be valid, then there would be an additional final step of hitting a 'run' button on the feed to actually run everything.

1. Navigate to the feed you want to add a node to
1. In the node graph for the feed, click on the node that you'd like to be the parent of the new node you are adding (in order to select it.)
1. While the target parent node is selected, click on a 'add new node' button in the right hand panel of the graph view.
1. A floating dialog appears docked to the right side of the screen. It will ask which plugin / pipeline to add, providing searchable lists of plugins / pipelines for the user to choose from. The user clicks next.
1. The second page of the floating dialog is the user's opportunity to fill in required parameters without defaults as well as review the parameters that are optional and/or have defaults in order to provide values for those as well. The user clicks 'add node'
1. The node is added to the graph, greyed out at first. As it begins to run, the node circle begins to pulse to indicate it is processing.
1. The user can at this point opt to add another node to the graph. They can add a node to the processing node as well, but it will be queued until the processing node completes (it can't run because it depends on the output of the processing node.) Queued nodes will show up as greyed out with dashed connector lines to indicate that they are queued. 
1. The processing node completes, its circle stops pulsing, and it appears at full opacity on the graph as any other completed node.
1. The next queued child node of the recently completed node will begin to pulse as it processes.

**Comment by mairin** [comment]
Here are some initial draft mockups demonstrating how this might work. They bring up additional discussion points. A few things to note up front:

* The example plugin is the MPC plugin from the Summit demo, and the parameters are the same as documented in the plugin.
* I left out the OpenShift specific parameters (e.g. max/min cpu/memory/etc.) but the option to tweak these could probably be added here.

# Starting the add node process
User navigates to the node which will be the parent node for the new node being added and click the 'add node' button.
![dialog_add-new-nodes_step1](https://user-images.githubusercontent.com/799683/59353436-f9a6ab00-8cf0-11e9-98db-1d75c50505cd.png)

# First screen of the add node wizard
This asks for basic details about the new node - what plugin will it use. For MVP you may only add a plugin, not a pipeline. (Pipeline to be selectable later on.) 
![dialog_add-new-nodes_step2-wiz1](https://user-images.githubusercontent.com/799683/59353447-00352280-8cf1-11e9-8995-cbdda8cdf5bc.png)

# Second screen of the add node wizard - autogen UI For pa
![dialog_add-new-nodes_step3-wiz2_AUTO](https://user-images.githubusercontent.com/799683/59353466-07f4c700-8cf1-11e9-966b-ba0c6c9bf33a.png)

![dialog_add-new-nodes_step3-wiz2a_CUSTOM](https://user-images.githubusercontent.com/799683/59353470-0aefb780-8cf1-11e9-927a-c62ec8c12d5e.png)

![dialog_add-new-nodes_step3-wiz2b_CUSTOM](https://user-images.githubusercontent.com/799683/59353474-0deaa800-8cf1-11e9-8cc7-1b1fc7693484.png)

**Comment by mairin** [comment]
# Potential MVP solution to config UI conundrum

After a lot of discussion with different teams at Red Hat that have a similar challenge wrt providing configuration for 3rd party tools within a platform, I do believe the ultimate right solution is to provide a custom templating ability per plugin configuration form, and set a high bar / good example for how those are constructed by intentionally designing a set of highest-visibility plugins' configuration forms for them as well as populating plugin developer docs with ample links to the source for these good examples.

The problem is, for an MVP scope, solving this issue technically isn't very minimal! It's a big issue - we have to figure out what kind of templating language / form we would use for the custom forms, then figure out how to load them into the JS-based UI from the plugin, and how to populate them with the data.

**So for MVP  the proposal here would be per plugin, to just provide a single large text input the user can enter the same arguments they would if the plugin was being run command line.** We could output a list of possible arguments they could use adjacent to the field. This sidesteps argument interdependency issues, and gives us more time to figure out a solution for enabling templating for proper html forms.

**Comment by mairin** [comment]
Current work in progress of the screen under discussion - this is the RAW cli input version
![dialog_add-new-nodes_step3-wiz2_RAW](https://user-images.githubusercontent.com/799683/61308089-809de600-a7bd-11e9-8e5a-15a8fe338e84.png)

**Comment by rudolphpienaar** [comment]
Is the latest/current design consideration?

**Comment by mairin** [comment]
@rudolphpienaar it's not - this one is still in product, not ready for review yet. (Sorry I must have mistagged it.)

**Comment by mairin** [comment]
# Updated Step 1 for Add Node
This mockup is pretty solid and I'd say ready for implementation. I've updated it to reflect the feed details redesign. (Step 2 / screen 2 incoming in the next few hours)

![dialog_add-new-nodes_step1](https://user-images.githubusercontent.com/799683/62648372-a59afa00-b920-11e9-8324-6a916ab14313.png)

**Comment by mairin** [comment]
# Updated Step 2 for Add Node

![dialog_add-new-nodes_step2](https://user-images.githubusercontent.com/799683/62649950-c1ec6600-b923-11e9-8dd4-be45cd16f4d6.png)
