### ISSUE TITLE
Analysis Catalog Page

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#344]
Add a plugin version and a search bar to the page for quick lookups.

**Comment by atharmohammad** [comment]
> Add a plugin version and a search bar to the page for quick lookups.

Is this issue still open , I am already seeing search bar on the analysis catalog page for plugins,pipelines and compute. If it is still open can you give a little more explanation about the issue

**Comment by PintoGideon** [comment]
Hey @atharmohammad , This feature has been implemented
