### ISSUE TITLE
Add API methods to ChRIS Store to support displaying metadata from the ChRIS store in the core ChRIS UI for installed plugins

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#352]
The idea for this came from the ChRIS weekly status meeting on 27 Jan 2022.

The ChRIS Store has additional metadata for installed plugins that isn't available in the plugin definition file and so isn't available for display in the core ChRIS UI. For example, the ChRIS store has the README file for the plugin. 

It would be very nice to have this additional metadata available to the ChRIS core UI, by having an API exposed in the ChRIS store so that a ChRIS core UI could retrieve the metadata from the ChRIS store.

**Comment by reeshi-18** [comment]
I would like to pickup this issue to contribute to this project as a part of Outreachy'22

**Comment by jennydaman** [comment]
@mairin can you add more details about the proposed feature?

**Comment by reeshi-18** [comment]
@mairin  please add some details to the issue so that I can start working on this

**Comment by jennydaman** [comment]
@reeshi-18 the ChRIS Store, https://chrisstore.co, is a repository of ChRIS plugins. Plugins are added from the ChRIS Store to a ChRIS backend.

The ChRIS_ui displays some information about plugins, but perhaps more information can be shown. See in the ChRIS_uii, in the sidebar click "Analysis Catalog" > "Plugins" and click on any plugin card to expand its details. Please propose and implement a feature which can improve this information display.

![image](https://user-images.githubusercontent.com/20404439/162140052-db722e47-58b1-4a28-8a63-33b2649f7c7c.png)

**Comment by jennydaman** [comment]
Here is an easy suggestion: add something to the popup panel along the lines of

```html
<a href={`https://chrisstore.co/plugins?q=${pluginName}`}>Search for me in chrisstore.co</a>
```

**Comment by reeshi-18** [comment]
do i need to setup chris plugins repo for the same? @jennydaman 
I already have chris ui and minichris setup in my local

**Comment by jennydaman** [comment]
Sorry I don't understand, what do you mean by "setup chris plugins repo?"

To work on this issue, running just ChRIS_ui and miniChRIS should be sufficient.

**Comment by Prakashh21** [comment]
@reeshi-18  would you like to collaborate with me on this ?, I had some ideas as to what else we can put on there , in the drawer card.

**Comment by somya51p** [comment]
> Here is an easy suggestion: add something to the popup panel along the lines of
> 
> ```
> <a href={`https://chrisstore.co/plugins?q=${pluginName}`}>Search for me in chrisstore.co</a>
> ```

@jennydaman Nice suggestion, we can add data as a popup or additional card. Can you specify exactly which additional metadata for the installed plugin from the ChRIS store is to be rendered on the ChRIS core UI?

**Comment by Seundede** [comment]
@jennydaman if this issue is still open, I'll like to work on it.
