### ISSUE TITLE
[Docs] Installation Docs giving Error

### ISSUE THREAD

**Issue by atharmohammad** [FNNDSC/ChRIS_ui#362]
Command ```docker run --rm -it -v $PWD:/home/localuser -p 3000:3000 -u $(id -u):$(id -g) --userns=host --name chris_ui fnndsc/chris_ui:dev``` is giving error 
```
$ docker run --rm -it -v $PWD:/home/localuser -p 3000:3000 -u $(id -u):$(id -g) --userns=host --name chris_ui fnndsc/chris_ui:dev
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```
Can admin confirm this issue , it is working for me if i run it using Quotes like below
```
$ docker run --rm -it -v "$PWD:/home/localuser" -p 3000:3000 -u $(id -u):$(id -g) --userns=host --name chris_ui fnndsc/chris_ui:dev
```

**Comment by jennydaman** [comment]
I'm guessing you have space characters in your `$PWD`?

Adding quotes around it is the way to fix it. But while spaces are legal characters in path names, it's typically frowned upon (because devs like me are too lazy to add quotes).

**Comment by atharmohammad** [comment]
> I'm guessing you have space characters in your `$PWD`?
> 
> Adding quotes around it is the way to fix it. But while spaces are legal characters in path names, it's typically frowned upon (because devs like me are too lazy to add quotes).

Okay , Thanks .. I will be closing this issue then !
