### ISSUE TITLE
Stray Paranthesis in left bottom of My analysis page in the ChRis dashboard

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#366]
Go to the **My analysis Page** in the **ChRis_ui dashboard** , go to the left most bottom , scroll if needed you'll se a Paranthesis.

![photo_2022-03-29_18-39-18-3](https://user-images.githubusercontent.com/90280586/160662039-6b4478ce-4b37-4b1c-8201-2f2fdb78ec6f.jpg)

**Comment by jennydaman** [comment]
Fixed in #367
