### ISSUE TITLE
Broken Padding on "Choose Files..." button 

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#368]
Broken Padding on "Choose Files..." button in Create New Analysis Page , When Trying to decrease the width of the screen.
![photo_2022-03-31_00-35-03-4](https://user-images.githubusercontent.com/90280586/160911825-37dc22d4-94c6-4985-927d-b0ddb4f3a85c.jpg)

**Comment by ydv-sahitya** [comment]
can I take this?

**Comment by arpit-maurya** [comment]
@ydv-sahitya - look loosely PR is already generate by @Prakashh21

**Comment by ydv-sahitya** [comment]
ok

**Comment by jennydaman** [comment]
Closed by #369
