### ISSUE TITLE
"Patient ID or MRN" text not showing up in mobile version and  Broken padding on (Pack Service orthanc)  button. 

### ISSUE THREAD

**Issue by ydv-sahitya** [FNNDSC/ChRIS_ui#371]
'Patient ID or MRN ' on the PAC page. this text is not showing up. when trying in mobile version.  and the "Pack Service Orthanc button'  is broken where I am trying to decrease the width of the screen.
 

![Untitled-2022-03-02-0308](https://user-images.githubusercontent.com/37513489/161255594-83b54d01-cced-479c-8091-259ed05c32f0.png)

**Comment by ydv-sahitya** [comment]
I am fixing these issues.

**Comment by Prakashh21** [comment]
Hey @ydv-sahitya did you tried recreating those bugs in the deployed project website -- https://app.chrisproject.org/login?then=/ 
I think they are already fixed , please check once because I also discovered those bugs , I also found those bugs but I was unable to recreate them in the deployed website.

**Comment by somya51p** [comment]
@ydv-sahitya Are you still working on this issue, want to collaborate?

**Comment by ydv-sahitya** [comment]
> @ydv-sahitya Are you still working on this issue, want to collaborate?

hi we can I am still working on it

**Comment by codeEmpress1** [comment]
Hi @ydv-sahitya @somya51p are you still working on this? I want to look into it. I am open to collaboration.

**Comment by codeEmpress1** [comment]
Hi @jennydaman, I have started working on this issue.

**Comment by Quintinus98** [comment]
Hello @codeEmpress1 are you still working on this project? I want to collaborate.

**Comment by codeEmpress1** [comment]
@Quintinus98 I am done with this issue. I am just waiting for review. We can however collaborate on other issues.

**Comment by Quintinus98** [comment]
Okay that would be fine @codeEmpress1. Just let me know when you have something we can collaborate on.
