### ISSUE TITLE
Items not aligned "Upload a Pipeline" button and "search box"

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#375]
In the **Analysis catalog** page , **"Upload a pipeline"** Button  and **"search box"** alignment not adequate items stuck in bottom , uneven padding in pipeline.
![Screenshot from 2022-04-02 07-52-50 1](https://user-images.githubusercontent.com/90280586/161362793-fbb3a7b5-8272-4cae-91e6-5e1659af3cc4.png)

**Comment by ShrutiKoli19** [comment]
Hey! I would like to work on this issue.

**Comment by ydv-sahitya** [comment]
@Prakashh21  can you give your email. I want to talk to you something.

**Comment by Prakashh21** [comment]
> @Prakashh21 can you give your email. I want to talk to you something.

Hey @ydv-sahitya we can talk on element see you there !!

**Comment by Prakashh21** [comment]
> Hey! I would like to work on this issue.

Hi @ShrutiKoli19 I've generated a PR for this one , take a look at it..  tell me if you have any feedback.
