### ISSUE TITLE
Unable to navigate from My Library tab

### ISSUE THREAD

**Issue by archijaiswal** [FNNDSC/ChRIS_ui#378]
Nav bar isn't showing up in the desired way after navigating to My Library tab.

https://user-images.githubusercontent.com/67463253/161421662-8d83dc21-f366-421e-830a-3a84f40b06ca.mp4

**Comment by archijaiswal** [comment]
Hey @jennydaman,I would like to fix this issue.

**Comment by reeshi-18** [comment]
@archijaiswal this might be possibly due to some issues in the phone!

**Comment by Prakashh21** [comment]
hey @archijaiswal were you able to recreate this bug on any other mobile device ?

**Comment by archijaiswal** [comment]
Hey @reeshi-18 & @Prakashh21, thank you for checking this out. Yes, I was able to recretae this bug on other mobile devices (iPhone ,Android) and on different PC with different OS(Linux,Windows) after resizing the size of browser. I'm unable to figure out why is it happening for me. I would appreciate if someone else too try to recreate this bug.

**Comment by Prakashh21** [comment]
Hey @archijaiswal I wasn't able to recreate this, I am using a xiaomi phone(Redmi note 7 pro) I'm attaching the screenshots ,  or using chrome dev tools any more details as to how to go about recreating this ??


![photo_2022-04-05_23-07-31](https://user-images.githubusercontent.com/90280586/161816783-cdb31a3a-e3bc-4f6a-88eb-9006688a3006.jpg)


![Screenshot from 2022-04-05 23-09-52](https://user-images.githubusercontent.com/90280586/161817047-4b45482e-8d02-4e2c-aad9-565b2d17c49e.png)

**Comment by archijaiswal** [comment]
Glad to inform that the bug seems to resolve by itself. I think this was probably due to the difference in version.(It was automatically loading with version 3.1.3 in my case and 3.1.4 in yours).
Thanks a lot @Prakashh21 :)

**Comment by Prakashh21** [comment]
> 

Ya , exactly that was the case ! in 3.1.4 it got fixed , later on I was able recreate this on my local environment , it was on version 3.1.3.
