### ISSUE TITLE
Start A Visit Before Accessing Patient Data.

### ISSUE THREAD

**Issue by sherrif10** [FNNDSC/ChRIS_ui#381]
Hey @jennydaman  @mairin  , am not sure if with in the system we have a functionality of starting a visit, however i feel like a given user to access patient data, it would look more of authentication to first start a visit, when  there is an active visit, then its is direct. currently there is no that functionality, Am willing to have more discussions on it. Thanks.

**Comment by jennydaman** [comment]
Hi @sherrif10, I'm not understanding you. What is a visit?

Regarding authentication: currently, the _ChRIS_ backend implements a relatively simple permissions model, where user accounts can be created anonymously, and all users can access the PACS. The rationale behind the lack of restrictions is to support open science and data sharing. When _ChRIS_ is deployed on a hospital's internal network, authentication/authorization is inferred by network access.

**Comment by sherrif10** [comment]
Thanks @jennydaman

**Comment by rudolphpienaar** [comment]
I'm not sure you fully understand how ChRIS relates to data? ChRIS is 
not an Electronic Health Record. I'm not sure what "a patient comes in 
without recording patient data" means.

ChRIS is a platform for collecting, organizing, and 
processing/scheduling "data" and "compute". By definition data MUST 
exist for ChRIS to interact with it. If a "patient" visits a hospital 
but no data is recorded (whatever that might mean) then this patient 
does not exist as far as ChRIS is concerned.

**Comment by jennydaman** [comment]
@sherrif10 another way to put it is: the data in ChRIS or to be added to ChRIS might come from your laptop, the internet, an MRI machine, ... In the case where it's clinical data, the "patient visit" happened already: it could've happened a minute ago, it could've happened 10 years ago. After data is put into EHR (could be outpatient discharge), it is then added to ChRIS.

**Comment by sherrif10** [comment]
ohh yes that sounds awesome.Thanks @jennydaman  for clarification.
