### ISSUE TITLE
Test the library Page 

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#383]
The library page is in it's initial rewrite. A lot of the features need to be tested.

It would be great to have data points on the following:

1. Check if browsing of the files is convenient and bug free.
2. Check if clicking on 'Read more folders' displays accurate results (Pagination)
3. Check if the loading spinners are displayed correctly
4. List down further improvements that can be made to this page
5.  Try uploading files using the 'upload' button.

Remember, the code is in the first draft so there are multiple improvements that can be made. Feel free to suggest them in the comments. The code for the library can be found here: https://github.com/FNNDSC/ChRIS_ui/tree/master/src/pages/DataLibrary

Suggestions for UI/UX improvements and bug fixes to the code are also most welcome.

![screenshot](https://user-images.githubusercontent.com/15992276/162005501-7e2bd2a6-a8cb-4450-8140-e9cc5312bb91.png)

**Comment by PintoGideon** [comment]
Also, the code for the library is here: https://github.com/FNNDSC/ChRIS_ui/tree/master/src/pages/DataLibrary

Improvements and bug fixes to the code are also most welcome.

**Comment by AryaArunB** [comment]
@PintoGideon I would like to work on this issue.

**Comment by PintoGideon** [comment]
@AryaArunB  Feel free to post your findings in the comment section so I can create issues over bugs you find and assign dev's to work on it.Thanks for taking this issue up. Looking forward to your suggestions.

**Comment by AryaArunB** [comment]
@PintoGideon  one of the problems that I am facing is I am not able to download the file via using the download option which appears when we click on the three dots. Another issue is that when I click the boxes under the Uploaded Files section the new page doesn't opens rather I would have to click on the name of the file.

**Comment by AryaArunB** [comment]
I think it's better to preview the image file once we click on the box itself rather than clicking on the preview icon.

**Comment by PintoGideon** [comment]
Great observations so far @AryaArunB . I will create an issue for that.

**Comment by AryaArunB** [comment]
@PintoGideon when I open the My Library tab the page automatically scrolls down while this doesn't happen with any other tabs.

**Comment by PintoGideon** [comment]
Hey @AryaArunB  Are you testing this on https://app.chrisproject.org.

**Comment by AryaArunB** [comment]
@PintoGideon I was able to upload files on the local copy of the project but I am not able to do the same on https://app.chrisproject.org/

**Comment by PintoGideon** [comment]
@AryaArunB , Thanks  !!!! I'll quickly fix it :)
