### ISSUE TITLE
Broken Button "Delete a Pipeline" in the Analysis Catalog Page

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#385]
**Steps to Reproduce**

This Bug is Present in the Pipelines section of the "Analysis Catalog" page ,
**You will need have pipelines uploaded to see this bug , If you are running minChris as a backend then you'll not see anything in the Pipelines section , because miniChris doesnot has pipelines preuploaded , to upload pipelines refer this --** https://github.com/FNNDSC/caw#testing

After you have your pipelines uploaded go to the "Pipelines" section of "Analysis Catalog" page and **select any  pipeline** , **you'll see a delete pipeline button** , **now on reducing the width of the screen the button will break** , **also you can use chrome Devtools to open the mobile version of the website to see this bug.** I am attaching the screenshots of both take a look.

![bug analysis catalog page](https://user-images.githubusercontent.com/90280586/162122586-67877b58-0a25-4328-bb46-8e567b87f270.png)

**Comment by Prakashh21** [comment]
I'm on this ! @PintoGideon

**Comment by PintoGideon** [comment]
@Prakashh21  Thanks for your work on fixing these issues.
