### ISSUE TITLE
Source build version and date from CI environment

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#394]
During the Outreachy applicants meeting on 2022-04-11 we did a walkthrough of a quick feature: changing a hard-coded string to instead be sourced from an environment variable.

Initial work has been done on the [envver](https://github.com/FNNDSC/ChRIS_ui/tree/envver) branch.

Here are the remaining steps to make this practical:

- [x] have build date be automatically determined at build time
- [x] set the build version and build date in the continuous integration environment (build version should be based on [`github.ref`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), [example](https://github.com/FNNDSC/pl-mri-preview/blob/bed9c5ae320ec0094c9e700d3fa550fc657618d4/.github/workflows/ci.yml#L35-L36)
- [x] in [.env](https://github.com/FNNDSC/ChRIS_ui/blob/master/.env) set a default value for version, e.g. `REACT_APP_CHRIS_UI_VERSION=unknown`

**Comment by aparna-bhatt** [comment]
Hey @jennydaman I am an outreachy applicant and willing to work on this issue.

**Comment by Anirudh4583** [comment]
@aparna-bhatt are you working on this issue?

**Comment by aparna-bhatt** [comment]
Yes @Anirudh4583 , do you have any suggestions feel free to discuss.
