### ISSUE TITLE
Login and Singup forms have different alert banners.

### ISSUE THREAD

**Issue by aparna-bhatt** [FNNDSC/ChRIS_ui#395]
## In Login

<img src="https://user-images.githubusercontent.com/86338542/162957629-2cbec411-d4b7-4546-80bf-30a5dfdf73ea.png" width="300" height="400" />

## In Signup
<img src="https://user-images.githubusercontent.com/86338542/162957972-1e3976ba-2eb4-4846-9244-1206bf03c736.png" width="300" height="400" />

**Comment by aparna-bhatt** [comment]
@jennydaman I have made a pull request . If you find any issue in it please let me know.Thanks!

**Comment by jennydaman** [comment]
Fixed in #400
