### ISSUE TITLE
Alert banner 

### ISSUE THREAD

**Issue by aparna-bhatt** [FNNDSC/ChRIS_ui#399]
The alert banner is not responsive.
<img src="https://user-images.githubusercontent.com/86338542/163039334-1ab63937-64e0-45ad-bb9c-ebe08bd4a078.png" width="400" height="400">

**Comment by ritikalohia** [comment]
@jennydaman, I have resolved this issue. Can I make a PR for it?

**Comment by aparna-bhatt** [comment]
@ritikalohia this issue has been resolved .You can see other issues.
