### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by AryaArunB** [FNNDSC/ChRIS_ui#402]
When the back button in clicked then we are out of the application but when tried to click forward button on the browser we are automatically logged in. I think we should automatically get logged out once back is pressed. What do you think @PintoGideon , @jennydaman?  

https://user-images.githubusercontent.com/60646682/163309919-c0dfff3b-97b4-4e90-abcd-5b3978a9d7ad.mov

**Comment by jennydaman** [comment]
There are indeed some issues with the login page: see https://github.com/FNNDSC/ChRIS_ui/pull/320 (this PR was not merged into master).

The user is not "automatically logged in" by clicking forward, the browser is simply restoring the cached webpage from when you clicked back. It's not a security issue.

I just tried this on bankofamerica.com, clicking back doesn't log out out.

Being logged out automatically when you click back would improve security in the sense that not being logged in improves security. But I don't think we should be giving up the functionality of the back button.
