### ISSUE TITLE
Update URI while nagivating in My Library

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#405]
Clicking into directories in the "My Library" view does not change the URI. Updating the URI on change would be a nice feature to have because then users would be able to share views of subdirectories by copy-pasting from the address bar. Also, users who like to middle-click and open in new tab would be able to middle-click on a directory and have it open in the new tab instead of opening the root in the new tab.

**Comment by Anirudh4583** [comment]
Hey @jennydaman, I would like to work on this issue. Can you please assign it to me.

**Comment by psalmuelle** [comment]
Hey @jennydaman , I can get this done. Can you please assign this issue me?

**Comment by Cecilia0109** [comment]
Hey @jennydaman, is this issue fixed? can I do something to improve it?

**Comment by Chisomnwa** [comment]
Hello @jennydaman, has this issue been solved? I would love to help with this issue. 

Can you assign this issue to me?

I don't also mind collaborating with someone to solve this issue.

I am waiting for your reply. Thank you.

**Comment by ciradu2204** [comment]
Hi @psalmuelle, are you still working on the issue?

**Comment by betty-alagwu** [comment]
Hello @jennydaman, can you please assign this issue to me ? I noticed a solution hasn't been shipped yet, and I am already doing research around it and would love to start working on a solution.

Thank you.
