### ISSUE TITLE
Required to Re-Authenticate !

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#408]
**ISSUE**

while using the chris_ui , if users decide to open some other section of the page in a new tab , they'll be required to Re-Authenticate.

**IDEAL BEHAVIOUR**

once logged in , Re-authentication should not be required.

I have added the Gif of the issue below ! take a look !
  

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/90280586/163692604-1f96c683-3cce-4e94-a1c6-9d3a226eb194.gif)

**Comment by AryaArunB** [comment]
I think this occurs only when you press control while you click on the sidebar buttons otherwise it works fine.

**Comment by AryaArunB** [comment]
@Prakashh21  I think one way is to make the PrivateRoute in routes.tsx Route. But this is a dumb way as there will be a security flaw the other way is to use cookies imo.

**Comment by Prakashh21** [comment]
> I think this occurs only when you press control while you click on the sidebar buttons otherwise it works fine.

Hi @AryaArunB I used middle mouse button.

**Comment by jennydaman** [comment]
Duplicate of https://github.com/FNNDSC/ChRIS_ui/issues/287, fixed in https://github.com/FNNDSC/ChRIS_ui/pull/320 but it was never merged successfully into master — we can keep this issue open.
