### ISSUE TITLE
Responsiveness of Dashboard Cards.

### ISSUE THREAD

**Issue by aparna-bhatt** [FNNDSC/ChRIS_ui#412]
The images been displayed on the dashboard are not responsive even in the full desktop site.
### SCREENSHOT
![Screenshot from 2022-04-18 23-29-22](https://user-images.githubusercontent.com/86338542/163852864-5ffe88a2-091c-4b95-983e-8e99ac5c1dcb.png)
The third image get hidden.

**Comment by Akanksha2403** [comment]
Hey @aparna-bhatt  I would like to work on this issue. can you assign it to me?

**Comment by aparna-bhatt** [comment]
Hey @Akanksha2403 I am a fellow contributor and I have opened this issue and solved it.You can solve some other issues.

**Comment by aparna-bhatt** [comment]
@jennydaman sir can you review my PR #413

**Comment by AryaArunB** [comment]
Hey @aparna-bhatt I think making a carousel/ collage of these pictures might help in making this responsive. I have tried to make a carousel for the same #391

**Comment by aparna-bhatt** [comment]
Yeah I think carousel is looking fine .
