### ISSUE TITLE
search box and button hidden behind the drawer

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ui#418]
**Issue**

This is a design flaw that compromises usability , In the analysis catalog page , on clicking one of the plugins , pipelines or hosts the drawer , pops up across the entire length of the section  and it , overshadows the search box and the button (in the pipelines section ) and hides the plugins behind it , until the user closes that drawer , search bar and button can't be accessed , this issue would be even worse if we have more number of plugins

**Ideal Behaviour**

The drawer should not hide the search bar and the button behind it , the user should be able to access the search box , while the drawer is open . If any one have any ideas as to what should be perfect solution that would strike a balance between design and usability , then please give suggestions!

                                                                                                                                                  
![Untitled drawing (14)](https://user-images.githubusercontent.com/90280586/164013806-baa9b28e-fb18-4b8c-8eee-13c6495dd45f.png)

**Comment by Prakashh21** [comment]
@mairin do you have any insights on this one..

**Comment by Ogalo** [comment]
@jennydaman I am an OutReachy applicant I would like to contribute to this issue? If you don't

**Comment by Quintinus98** [comment]
@jennydaman I would like to contribute to this issue, I am an Outreachy Applicant

**Comment by Cecilia0109** [comment]
I would like to contribute to this issue, I am an Outreachy Applicant @jennydaman

**Comment by haszankauna** [comment]
Hello @Prakashh21 I am an outreachy applicant and will love to work on this

**Comment by codeEmpress1** [comment]
@haszankauna @Dev-Comfie @Cecilia0109 @Ogalo @Quintinus98  I raised a PR for this. Reviews and comments are welcome.
