### ISSUE TITLE
Button of 'My Library' is not scaled in different screen resolution

### ISSUE THREAD

**Issue by singhavs** [FNNDSC/ChRIS_ui#424]
### Problem

![f695c809-4cf9-4419-9996-712d420a884e](https://user-images.githubusercontent.com/67657066/164396741-1ff907a4-d203-4dc0-b1e1-1d1ce81ad23a.jpg)

**Comment by asaayushisingh** [comment]
Hey! @PintoGideon Can I work on this issue?

**Comment by PintoGideon** [comment]
Sure !!

**Comment by Seundede** [comment]
@PintoGideon, can I work on this issue?
