### ISSUE TITLE
Button of "My Analyses"  responsive error

### ISSUE THREAD

**Issue by singhavs** [FNNDSC/ChRIS_ui#426]
### Problem
Button of "My Analyses"  has responsive error at different screen resolution
![fin1](https://user-images.githubusercontent.com/67657066/164675601-00795c03-ade7-49ce-b0a9-940eb9e6b30a.png)

**Comment by Beyond-Logic** [comment]
Hi, Can I be assigned this task. I am an Outreachy Applicant interested in contributing to this ChRIS_ui project
I have seen the feeds page and the Create New Analysis button sure needs a fix from around a screen size of < 769px, which I can be able to do giving my experience with react.

**Comment by Beyond-Logic** [comment]
I will be working on this task.
