### ISSUE TITLE
A lot of information is being stored in state

### ISSUE THREAD

**Issue by Anirudh4583** [FNNDSC/ChRIS_ui#429]
Browsing through folders and files requires the current path and list of nested items, which are currently being stored in context state. The state is updated for every folder click and new paths are pushed on. This can easily create overhead when a lot of folders are opened one after another as the state is not cleared in this case.

**Screenshot**:
![image](https://user-images.githubusercontent.com/34450549/164706432-44b00ed0-c623-4b16-91e6-feaab1b2c3a0.png)
![image](https://user-images.githubusercontent.com/34450549/164708618-36ce5c49-d99b-4cbd-94bd-2f70a823b684.png)

**Minimum effort solution**:
Clear the previous state every time the folder path is updated.

**Best solution IMO**:
Switch the entire folder fetching and opening logic to use URL path and search queries instead of the state. Additional benefits are also there, less number of renders and state updates, better performance on slower devices and ~1/3rd network calls.

**Comment by PintoGideon** [comment]
Hey @zrthxn , The browser UI has since been completely written and I have taken the minimum effort solution of clearing the previous state every time the folder path is updated. Using the browser history to keep track of the states lead to a lot of bugs in the previous UI.

**Comment by Anirudh4583** [comment]
Hey @zrthxn @PintoGideon, can you guys take a look at #423.

**Comment by PintoGideon** [comment]
Hey @Anirudh4583  Have you tested that PR against new updates to that page recently ?

**Comment by Anirudh4583** [comment]
Sure, I'll take a look!
