### ISSUE TITLE
(CHRIS UI - P3 - DESIGN) Add cancel and/or delete buttons per node in feed details.

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#45]
Add cancel and/or delete buttons per node in feed details. (Cancelling a node also cancels all nodes that follow it in its tree branch)

**Comment by DivyanshiSingh** [comment]
@mairin this one is great to work on. I would like to work on this issue. Please assign me this issue.

**Comment by somya51p** [comment]
Hey @mairin @PintoGideon. Can I take up this issue to work on?

**Comment by swagatikapanda123** [comment]
Hey @marini I would like to contribute to this issue as a part of Outrichy 22. Please assign this task to me

**Comment by mairin** [comment]
@swagatikapanda123 Sorry for the confusion - it seems this one is fixed already so I am going to close the issue.
