### ISSUE TITLE
Issues Without Proper Description

### ISSUE THREAD

**Issue by bennaaym** [FNNDSC/ChRIS_ui#543]
Hello folks, I'm new to the ChRIS project and would like to contribute to this repository, but while browsing through the issues, I notice that most of the issues don't have a proper description, making it difficult for new contributors to work on these issues. Also, some of the issues already have open PRs associated with them, but it doesn't show up on the issues page because the PR didn't specify that it's related to the issue.

**PS**: I'm new here, so I'm not sure if this is the right place to raise this issue. Please let me know if there is a better place to mention this concern.

**Comment by PintoGideon** [comment]
Hey there @bennaaym , Thanks for raising this issue. Currently, all the issues that are being raised are geared towards a release of the UI coming up shortly. These issues are a product of our internal team conversations and hence lack detailed descriptions. I will list down all the issues with detailed descriptions in a few days. Feel free to familiarize yourself with the codebase and suggest improvements to code patterns/ improvements in the meanwhile. You can also setup the backend and test the UI for bugs. All of the above will be incredibly meaningful to us and would also help you pick other issues in the future. Let me know what you think :)

**Comment by jennydaman** [comment]
Most issues here are informal and for internal tracking purposes.

Issues which we would like for collaborators to help with are either labeled as ["good first issue"](https://github.com/FNNDSC/ChRIS_ui/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), ["help wanted"](https://github.com/FNNDSC/ChRIS_ui/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22), and/or ["under the "Team-19" project](https://github.com/FNNDSC/ChRIS_ui/issues?q=is%3Aopen+is%3Aissue+project%3Afnndsc%2F6).

Please join us on Matrix to discuss: https://matrix.to/#/#chris-frontend:fedora.im

**Comment by bennaaym** [comment]
@PintoGideon, @jennydaman thank you all for your feedback. I'll be familiarizing myself with the code base and reach out to you through the matrix community if I need help. Please feel free to close this issue if necessary.
