### ISSUE TITLE
Compute resource selection does not work for FS plugin

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#554]
Creating a feed from the "Create New Analysis" wizard: after choosing an FS plugin to run, there is a screen to select a compute environment. Even though the dropdown menu works visually, the compute environment name is not sent with the request, and so I cannot create a FS plugin instance with a specific compute environment from ChRIS_ui.

**Comment by MdSahil-oss** [comment]
@jennydaman is this issue still exists ?

**Comment by jennydaman** [comment]
Sorry for not seeing your message earlier! Ping me on matrix next time if I don't respond.

Yes this issue is still a problem and it would be great if you could take a look at it. I think it should be low-hanging fruit.

**Comment by Chizycodes** [comment]
Hi @jennydaman, I am an outreachy applicant and will like to work on this issue.

**Comment by MdSahil-oss** [comment]
@Chizycodes go ahead and resolve it.

**Comment by NelsonAkonoafua** [comment]
Hi @jennydaman I would also like to work on this issue and see ways on how to improve on it

**Comment by Chizycodes** [comment]
@NelsonAkonoafua we can work on it together.

**Comment by NelsonAkonoafua** [comment]
Hey Joy. Nice to meet you. I'd like that. we should communicate better so
we know what steps to take. I want to know if you're using ubuntu yet with
the docker we were asked to download

**Comment by Chizycodes** [comment]
Yeah, I'm using Ubuntu. I tried recreating the issue, and I was able to create a feed. The payload sent only contained the dir value. But the feed created had all the details entered, including the compute environment. 

![Screenshot from 2022-10-12 04-09-30](https://user-images.githubusercontent.com/53119290/195241271-380bed95-5681-43e5-9a2d-21b37e5dacfd.png)

**Comment by codeEmpress1** [comment]
@Chizycodes was this done in development or production, I need help on how to get analysis to display in development, also I couldn't add new analysis.

**Comment by NelsonAkonoafua** [comment]
Just downloaded Ubunu actually. I want to install it and get started
tonight. Have just been wondering if to switch or use Ubuntu on a virtual
box. So give me a second so i get my utilities in order. I might want to
see a video of this though. So I know what is actually happening. I am
still kind of new to the project and will appreciate the help. I have only
done some light reading.

**Comment by Chizycodes** [comment]
@codeEmpress1 It was done in development. What error are you getting?

**Comment by Chizycodes** [comment]
Alright. @NelsonAkonoafua

**Comment by codeEmpress1** [comment]
@Chizycodes  When I login, there is no data displayed for analyses, pipelines, and so on. Every time I try to add analysis. It gets stuck at 80%.

**Comment by Chizycodes** [comment]
Yeah, I encountered a similar issue, it happens when you enter an invalid dir value. I had to upload an image on the library page first. If you're using chris login details, your dir value would be chris/uploads/<folder name> @codeEmpress1

**Comment by codeEmpress1** [comment]
Thank you @Chizycodes  I have been struggling with this

**Comment by jennydaman** [comment]
Hey @Chizycodes thanks for taking a look, sorry for my absence. I'll give you some guidance here on how to reproduce the issue.

Most generally, you need to have a FS plugin registered to more than one compute environment. By default, this is not going to exist.

Here are steps to reproduce. The first two steps can be performed manually by hand by going to http://localhost:8000/chris-admin/

1. Add a **compute resource** (e.g. name: dummy-cr, url: http://http://pfcon.host:5005/api/v1/, username: pfcon, password: pfcon1234)
2. Add a **plugin** e.g. https://chrisstore.co/api/v1/plugins/2/ to the two compute environments "host" and "dummy-cr"
3. In ChRIS_ui, create a new feed, select the option to run a FS plugin, choose the plugin "Anonymized reference MRI", and then choose the compute resource "dummy-cr"

Expected outcome: pl-mri10yr06mo01da_normal is executed on "dummy-cr"
Actual outcome: pl-mri10yr06mo01da_normal is executed on "host"

Here's a screenshot of what it'd look like on https://next.chrisproject.org

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/20404439/196037662-55218b5b-800c-47a6-af48-6b3b770c6bec.png">

Notice that I've selected the compute resource called "bu-21-9". Once I click "Create Feed", we see

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20404439/196037748-17344f63-ab99-4690-be59-40a27f47bc10.png">

Expected outcome: in the details pane it should say "Compute Environment: bu-21-9"
Actual outcome: it says "host"
