### ISSUE TITLE
Resizing the terminal in the Feed View

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#563]
![Screenshot from 2022-07-28 20-00-34](https://user-images.githubusercontent.com/15992276/181656442-c2ac40dd-f4ec-48e6-ba2c-6f2050a9716e.png)

**Comment by codeEmpress1** [comment]
Hi @PintoGideon, I am Alimot, an outreachy applicant. I will like to work on this issue. Can you please assign it to me?

**Comment by codeEmpress1** [comment]
I have been able to reproduce the issue, working on it now.
