### ISSUE TITLE
Improve css code quality throughout the web app

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#569]

**Comment by TateDeVito** [comment]
Hey @PintoGideon - I can take a look at this one if it is still open! Just let me know and I can get working.

**Comment by PintoGideon** [comment]
Hey @TateDeVito , this would be of great help. You have  full creative control as an when you propose/make changes.

**Comment by TateDeVito** [comment]
Appreciate it, and will get started! Thanks.

**Comment by TateDeVito** [comment]
Hey @PintoGideon - going through the CSS now. When you refer to **code quality**, is there anything specific you would like to see get cleaned up? Otherwise I can generally use my judgment to clean up wherever I can. 

Thanks!

**Comment by PintoGideon** [comment]
Hey @TateDeVito,

 The design patterns that come with scss aren't being leveraged well in the codebase. Currently, the css code is either written inline with jsx or the code is being reused.

The big issue that I was planning on tacking with this issue was to move the UI towards responsiveness. Feel free to start according to your judgement for now.

**Comment by PintoGideon** [comment]
My plan was a bit more laborious for this task. I was planning on going through every scss file or css style and question why it was being used. The codebase is small now to be able to do that before we write more features in. Thoughts/strategies would be appreciated.

**Comment by TateDeVito** [comment]
Hey @PintoGideon !

I just put up a PR for this issue here: https://github.com/FNNDSC/ChRIS_ui/pull/625

I tried to leave some comments in there to give you an idea of how I went about refactoring the stylesheets. Let me know if you want to discuss at all. 

Thanks!

**Comment by Cecilia0109** [comment]
Hey, @PintoGideon ! I am an outreachy applicant and I would like to solve this issue. 
Could you please assign this to me?

**Comment by codeEmpress1** [comment]
Hi @PintoGideon. I am Outreachy applicant. I will like to work on this. I can collaborate with @Cecilia0109 .

**Comment by Chizycodes** [comment]
Hi @PintoGideon I am an Outreachy applicant. I will like to work on this with @Cecilia0109  and @codeEmpress1 .

**Comment by JulianaSau** [comment]
Hi, I'd like to work on this issue too

**Comment by M0Hassan** [comment]
Hi @PintoGideon, am an outreachy applicant and I would like to collaborate on this issue.

**Comment by Dev-Comfie** [comment]
Hi @PintoGideon , I am an Outreachy applicant. I will like to collaborate on this issue. I can collaborate with anyone @codeEmpress1 @Chizycodes .

**Comment by haszankauna** [comment]
Hello, @PintoGideon  I am outreachy applicant and will love to work on this
