### ISSUE TITLE
Card tooltips per platform

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#576]

**Comment by TateDeVito** [comment]
Hey @rudolphpienaar! Wanted to check in on this issue and just get a description of what you are looking for.

Appreciate it!

**Comment by PintoGideon** [comment]
Hey @TateDeVito ,

When you visit the library page, you'll see tooltips describing actions on how to interact with the cards. You can click on the 'x' button to get rid of these tooltips. However, it was reported that these tooltips were not displayed on MacOS (probably safari as the default browser). Also, commands for different machines could look different for example `Ctrl + shift + click` would be` Cmd + shift + click`. Rudolph wanted to check if we could identify the type of browsers or machine and display the tooltip accordingly of if there were any other ideas.
