### ISSUE TITLE
Active state in Feed Table turns off if any nodes have error

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#584]
This error is a bit difficult to reproduce and fix. The active state in a feed table is indicated by different background color on each row. It is also indicated by a green color on the status chart at the end of the row. If a node errors out in the feed tree with other active nodes present, the expectation is to still have indicators for the active state in the feed table. However, the UI doesn't capture that.
 
This actually need to be fixed in the chris-upload utility written by @Sandip117 . I think the first step in this task would be reproduce this issue successfully.

![Screenshot from 2022-10-12 09-43-26](https://user-images.githubusercontent.com/15992276/195359021-7e0654d2-ba5f-435c-8914-336214daa785.png)

**Comment by jennydaman** [comment]
Awaiting further clarification on this issue.

I think it was about making a more prominent indication of which feeds contain failed plugin instances in the table view.

https://github.com/FNNDSC/ChRIS_ui/blob/master/src/pages/Feeds/components/FeedListView.tsx
https://www.patternfly.org/v4/components/table

(Looking at Patternfly docs, maybe we want to consider a [data list](https://www.patternfly.org/v4/components/data-list/design-guidelines/)?)
