### ISSUE TITLE
Issue with negative values and dates while adding a new node.

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_ui#61]
The parameter editor in the process of adding a node does not take in negative values and date in the format "yy-mm-dd".

Working on a fix.

**Comment by PintoGideon** [comment]
@jcaianirh Will check and give you an update today.

**Comment by PintoGideon** [comment]
![Issue_61](https://user-images.githubusercontent.com/15992276/74454790-67900d00-4e52-11ea-972d-3659918fae88.png)
