### ISSUE TITLE
Plugin instance parameter selection loading race condition

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#619]
priority: low

![screenshot](https://user-images.githubusercontent.com/20404439/187201768-8eaf91a9-5640-4ce5-872c-5a009db14d2d.png)

The response from `api/v1/plugins/N/parameters/` was slow for a stochastic reason. The wizard UI was interactable before the parameters data was loaded, so it said "You cannot more parameters to this plugin" but then a few seconds later, the (required) parameters popped up.

https://github.com/FNNDSC/ChRIS_ui/blob/59adf160b570e151b38e59e6a866e7b22ff2a9a4/src/components/feed/AddNode/GuidedConfig.tsx#L96

More technically, there are other possible reasons for `params` to be falsy here other than it representing an empty collection.

BTW let's also fix the English of this error message...

**Comment by codeEmpress1** [comment]
Hi @jennydaman, I am an outreachy applicant. I will like to work on this.

**Comment by Quintinus98** [comment]
Hello @jennydaman can i work on this issue?

**Comment by jennydaman** [comment]
@Quintinus98 please ask @codeEmpress1 if they would like to work together. I strongly encourage working together

**Comment by codeEmpress1** [comment]
@Quintinus98 I will like to work with you on the issue, can we have a pair programming section and figure it out together? Let me know your preferred time and I will work with it and create the meeting on my calendar. You can share your email for that. Thanks

**Comment by codeEmpress1** [comment]
@jennydaman I also have the same challenge as in #563 , I could not reproduce the error in development. I however tried it in production and found that the error message is only coming up when all parameters has been selected and the user tries adding another parameter, this I think should be the normal behaviour. However, I will take a deeper look at the constraint controlling this behaviour which you highlighted above. I have taken note of the correction ion the error message also.

**Comment by codeEmpress1** [comment]
@jennydaman I've been able to add analyses, I'm looking into the issue now

**Comment by Quintinus98** [comment]
Hello @codeEmpress1 I messaged you on Matrix. We can discuss the issue and and how to go about the solution.

**Comment by codeEmpress1** [comment]
@Quintinus98 I will check your message, I fixed this issue already, kindly check #682. However I found another issue while fixing it, I opened it in #683, and we can work on it together.
