### ISSUE TITLE
Plain text dates are wrong for the study dates

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#620]
The plaintext dates in the Pacs QR are incorrect. This could be a bug in cube , but this is speculation at this point from my end and needs to be looked into further

Actual Dates of the patient:

![image](https://user-images.githubusercontent.com/15992276/195356072-9b164998-e994-479b-8539-507aaef75828.png)
![image (1)](https://user-images.githubusercontent.com/15992276/195356117-bba837b1-71dd-45b2-a6cf-ab8d11db3639.png)

Found: The ChRIS GUI reports July for a scan date of June. This switch only happens for June and July. The dates for other months have been reported correctly.

This bug was reported by Jeff Stout and has always been present.

**Comment by AndroGenius-codes** [comment]
@jennydaman  I'd like to take a look at this issue if you don't mind

**Comment by Quintinus98** [comment]
Hello @PintoGideon @jennydaman @mairin Can I take up this issue? I am an Outreachy Applicant, I'd like to contribute on this project.

**Comment by rudolphpienaar** [comment]
This is not a apfdcm bug simply because pfdcm does not touch any date fields or do date processing.

**Comment by jennydaman** [comment]
@Quintinus98 , please ask @AndroGenius-codes if they would like to work together.

**Comment by Quintinus98** [comment]
Hello @AndroGenius-codes would you like to work on this issue together?

**Comment by AndroGenius-codes** [comment]
> Hello @AndroGenius-codes would you like to work on this issue together?

Sure thing. Sorry I am just seeing this

**Comment by Quintinus98** [comment]
Okay that's fine.
Let's chat on Matrix

**Comment by AndroGenius-codes** [comment]
> Okay that's fine. Let's chat on Matrix

What's your username

**Comment by Quintinus98** [comment]
My username is David Obodo
