### ISSUE TITLE
ChRIS UI tests

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#623]

**Comment by nanfuka** [comment]
hi @PintoGideon looks like this ticket has no description, kindly add some more desccription, I would like to take it on

**Comment by nanfuka** [comment]
am applicant for internship, I would like to take up testing of this system. kindly assign me to this ticket
My way of implementation is to test each component separately

**Comment by Seundede** [comment]
@jennydaman I'll like to work on writing integration tests.
