### ISSUE TITLE
Unified UI/X for compute flows

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#637]

**Comment by jennydaman** [comment]
@Quintinus98 vague issues lacking context such as these are not suitable for Outreachy applicants to work on.

If you would like some advice on ways to contribute to the ChRIS project, DM me on Matrix — we would appreciate your Python and back-end skills

**Comment by Quintinus98** [comment]
Okay Noted @jennydaman
