### ISSUE TITLE
Feed actions pane background color is cut off when you scroll down

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#640]
![screenshot](https://user-images.githubusercontent.com/20404439/193202231-81be4623-8022-4bfc-9afe-82fd2bc6a559.png)

**Comment by lumuchris256** [comment]
hey @jennydaman  am trying to reproduce the error on the online instance of chris

**Comment by lumuchris256** [comment]
![chris](https://user-images.githubusercontent.com/59338693/193881672-5c57dda0-3c8c-41b6-a121-7f0c0d556fcb.png)
need a few pointers to repsoduce

**Comment by jennydaman** [comment]
@lumuchris256 to reproduce this issue, please resize the viewport so that a scroll bar is necessary for the top-right section. 

Note that https://app.chrisproject.org is _not_ running an updated version of ChRIS_ui, rather, it's held back to an older commit for the sake of reliability. Please visit https://next.chrisproject.org instead to see an automatic build of the latest commit of master.

**Comment by Meldy2503** [comment]
Hello @jennydaman, I would like to work on this issue, can you please assign it to me, and guide me on what is expected

**Comment by TomisinAjayi** [comment]
Hi @jennydaman, I am an outreachy applicant and I would like to solve this issue. Thank you!

**Comment by lumuchris256** [comment]
i am currently working on this issue

**Comment by jennydaman** [comment]
Hello everyone,

In general collaboration leads to better results. @lumuchris256 it is up to you if you would like to work together on this issue, I would recommend looking into "pair programming."

**Comment by AnishaSingh0118** [comment]
Hello, 
Even I want to put in my efforts to find a solution for this issue.(I am an Outreachy applicant). 
Hoping to come up with perfect solution. Can I work even without this issue being assigned to me ?

**Comment by annicklinca** [comment]
hello @jennydaman  
i would like to solve this issue.

**Comment by Meldy2503** [comment]
@lumuchris256 hello, do you mind collaborating with me to work on this issue, please

**Comment by jennydaman** [comment]
@lumuchris256 how is it going on this issue? Please keep us in the loop. If I don't hear from you in 36 hours, I will re-assign this issue to someone else.

**Comment by Meldy2503** [comment]
Ok, let me start working on it immediately, I didn't know you approved the
collaboration, thanks for reaching out

**Comment by lumuchris256** [comment]
> @lumuchris256 how is it going on this issue? Please keep us in the loop. If I don't hear from you in 36 hours, I will re-assign this issue to someone else.

@jennydaman  unsign me so someone can get to work on it

**Comment by Meldy2503** [comment]
@jennydaman , I would love to work on this issue, please can you assign this issue to me

**Comment by Jolzyfx** [comment]
> @lumuchris256 how is it going on this issue? Please keep us in the loop. If I don't hear from you in 36 hours, I will re-assign this issue to someone else.

@jennydaman I would love to collaborate with on you this issue, please assign it to me

**Comment by dipanshuraz** [comment]
Hey @Jolzyfx I'm interested to work on this with you, @jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
@Meldy2503 apologies for the delay, you've been assigned! hopefully it's a quick fix.

**Comment by Meldy2503** [comment]
Thanks, on it
