### ISSUE TITLE
No confirmation or rejection for Sign Up in ChRIS store

### ISSUE THREAD

**Issue by qgatssdev** [FNNDSC/ChRIS_ui#645]
<img width="1423" alt="Screenshot 2022-10-10 at 10 52 35 AM" src="https://user-images.githubusercontent.com/79480742/194840267-3258439f-1c3e-41c3-8082-3bec692be50f.png">

On signing up, there's no confirmation modal or toast for successful sign up and unsuccessful sign up.

**Comment by AndroGenius-codes** [comment]
@jennydaman I'd also be interested in helping @qgatssdev to fix this.

**Comment by nbarnabee** [comment]
I think this may be related to the issue I just posted  - #646  - were you able to successfully sign up?

**Comment by AndroGenius-codes** [comment]
> I think this may be related to the issue I just posted - #646 - were you able to successfully sign up?

Yes I was. In order to sign up successfully you'll have to set up the backend. I.e minichris

**Comment by qgatssdev** [comment]
> I think this may be related to the issue I just posted - #646 - were you able to successfully sign up?

Yes but this wasn't on my localhost, i did this with the hosted site.

**Comment by AndroGenius-codes** [comment]
> > I think this may be related to the issue I just posted - #646 - were you able to successfully sign up?
> 
> Yes but this wasn't on my localhost, i did this with the hosted site.

Oh i haven't tried that one

**Comment by jennydaman** [comment]
@qgatssdev I have assigned you, it is up to you whether you would like to accept anybody else's help. I strongly encourage collaboration.

There are several problems here. If account creation is unsuccessful, an error message is displayed but then the page immediately refreshes so you don't get to read it.

Ideally, unsuccessful account creation would not refresh the page, and a successful account creation would also log you in and take you to the dashboard.

**Comment by qgatssdev** [comment]
> @qgatssdev I have assigned you, it is up to you whether you would like to accept anybody else's help. I strongly encourage collaboration.
> 
> There are several problems here. If account creation is unsuccessful, an error message is displayed but then the page immediately refreshes so you don't get to read it.
> 
> Ideally, unsuccessful account creation would not refresh the page, and a successful account creation would also log you in and take you to the dashboard.

Okay! no problem, @nbarnabee  are you still interested in collaborating?

**Comment by Jolzyfx** [comment]
> > @qgatssdev I have assigned you, it is up to you whether you would like to accept anybody else's help. I strongly encourage collaboration.
> > There are several problems here. If account creation is unsuccessful, an error message is displayed but then the page immediately refreshes so you don't get to read it.
> > Ideally, unsuccessful account creation would not refresh the page, and a successful account creation would also log you in and take you to the dashboard.
> 
> Okay! no problem, @nbarnabee are you still interested in collaborating?

@qgatssdev I'm interested in collaborating with you to solve this problem
