### ISSUE TITLE
Email validation error when signing up to ChRIS store

### ISSUE THREAD

**Issue by nbarnabee** [FNNDSC/ChRIS_ui#646]
When attempting to sign up to the ChRIS store, I received a validation error message - "This email is already registered." - which appeared for 3ms before page refresh.  I tried again, using a different email address, and received the same message.  I tried a third time, using a random string of characters formatted like an email address (e.g., afoiajosdf@pat.com) and received the same message.

Attempting to register using a random string that was not formatted like an email address returned the error "A valid email address is required," so some part of the validation is working.  However, once again the page refreshed immediately after submission and the information was lost.

**Comment by yaya-mamoudou** [comment]
Hello. I am an outreachy applicant. I wish to work on this issue

**Comment by Yekasumah** [comment]
i'm working on this issue.

**Comment by Quintinus98** [comment]
Hello @nbarnabee are you working on this issue? if not I would like to work on it.

**Comment by nbarnabee** [comment]
@Quintinus98 I'm not currently working on it, but you might want to coordinate with @Yekasumah

**Comment by Quintinus98** [comment]
@Yekasumah do you minid if we work on this issue together?

**Comment by Yekasumah** [comment]
@Quintinus98 Hi, i don't mind collaborating together

**Comment by Quintinus98** [comment]
Okay nice @Yekasumah I'll message you on the public chat Matrix

**Comment by haszankauna** [comment]
Hello, @nbarnabee I am an outreachy applicant and will love to work on this

**Comment by haszankauna** [comment]
hello @Yekasumah Do you mind if I join in collaborating on this project?

**Comment by Jolzyfx** [comment]
> page refresh. I tried again, using a different email address, and received the same message. I tried a third time, using a random string of characters formatted like an email address (e.g., [afoiajosdf@pat.com](mailto:afoiajosdf@pat.com)) and received the same message.

@nbarnabee I would love to collaborate with on you this issue, please assign it to me

**Comment by jennydaman** [comment]
A lot of people commenting here! Since @nbarnabee is the author of this issue, they have first call on whether they'd like to submit a contribution related to it.

Though I am not sure exactly what the bug is, could you explain it again? You mention the ChRIS store, which is a separate project — this is the ChRIS_ui repository.

If you're getting the error message "This email is already registered." This message is coming from the back-end. It might help to look into what request is being sent from the front-end to the back-end using devtools networking tab (press f12 in Chrome or Firefox).

**Comment by nbarnabee** [comment]
Oh, gosh, I'm really sorry for walking away from this.  I am very much a novice with regards GitHub workflows.  Lesson learned.

> Though I am not sure exactly what the bug is, could you explain it again? You mention the ChRIS store, which is a separate project — this is the ChRIS_ui repository.
> 
> If you're getting the error message "This email is already registered." This message is coming from the back-end. It might help to look into what request is being sent from the front-end to the back-end using devtools networking tab (press f12 in Chrome or Firefox).

With regards to this, yes, in hindsight I realize that I raised this issue in the wrong repository - I should have placed it in the ChRIS store repo and not in this one.  I also did not include enough information; I encountered the error while attempting to register at [](https://chrisstore.co/quickstart).  It is definitely a back-end validation error.  I'll go ahead and close this thread down; if anyone wants to take it up in the proper repo, please feel free!
