### ISSUE TITLE
Hint overflowing in pac look up mobile screen

### ISSUE THREAD

**Issue by codeEmpress1** [FNNDSC/ChRIS_ui#649]
<img width="154" alt="Screenshot 2022-10-10 at 17 17 14" src="https://user-images.githubusercontent.com/47438585/194891747-da2ed136-1f5a-4f4e-9e1d-a8e1983f2e70.png">

**Comment by codeEmpress1** [comment]
HI @jennydaman @mairin I found this issue and I will like to fix it.

**Comment by codeEmpress1** [comment]
I have started working on this

**Comment by AnishaSingh0118** [comment]
If this issue is not resolved yet, Can I work on it ?

**Comment by AnishaSingh0118** [comment]
> @AnishaSingh0118 I am working on it presently. Do you want to collaborate?

yes we can have good discussion over this issue, firstly let me reproduce it and will come back to you with an idea. :)

**Comment by codeEmpress1** [comment]
@jennydaman I raised a PR for this issue.
@AnishaSingh0118 you can check the PR I raised. You can make a review and make suggestions on how to make it better.

**Comment by AnishaSingh0118** [comment]
> @jennydaman I raised a PR for this issue. @AnishaSingh0118 you can check the PR I raised. You can make a review and make suggestions on how to make it better.

Could you attach some before and after snapshots for better understanding, it would be good for users to look at it and can easily grap it .

**Comment by codeEmpress1** [comment]
> > @jennydaman I raised a PR for this issue. @AnishaSingh0118 you can check the PR I raised. You can make a review and make suggestions on how to make it better.
> 
> Could you attach some before and after snapshots for better understanding, it would be good for users to look at it and can easily grasp it .

Ok @AnishaSingh0118 there is a before image in the issue. I will attach an after image here

**Comment by codeEmpress1** [comment]
Ok, I will, thank you!

**Comment by AnishaSingh0118** [comment]
> Ok, I will, thank you!

other than that everything looks fine.
