### ISSUE TITLE
CI/CD fix in the UI

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#652]

**Comment by Yekasumah** [comment]
I'm working on this issue

**Comment by jennydaman** [comment]
Hey @Yekasumah thank you for being interested in this issue. Quality assurance is important.

The build fix in https://github.com/FNNDSC/ChRIS_ui/commit/e56c9871848e44d85d9b750519e86191858703d9 has not been applied to our CI so Cypress fails in CI, please take a look at that.

**Comment by dipanshuraz** [comment]
Hi I'm an outreachy applicant, I want to work on this @jennydaman Please assign this to me

**Comment by Seundede** [comment]
#712
