### ISSUE TITLE
fix the UI for the date  picker in PACS Query/Retrieve

### ISSUE THREAD

**Issue by mightyFZeus** [FNNDSC/ChRIS_ui#653]
![Screenshot (94)](https://user-images.githubusercontent.com/67365597/194973191-1b9fb458-7974-4d97-a195-95498289c5c4.png)

**Comment by mightyFZeus** [comment]
i am working on this issue

**Comment by jennydaman** [comment]
Fixed https://github.com/FNNDSC/ChRIS_ui/pull/657
