### ISSUE TITLE
Create automatic releases

### ISSUE THREAD

**Issue by Njong392** [FNNDSC/ChRIS_ui#659]
I can see that the last time this repo got versioned was in 2021. Maybe we could set up automatic versioning, that gets updated and tracked through conventional commits. Here is a [helpful article](https://www.conventionalcommits.org/en/v1.0.0/) on conventional commits.

If this issue is approved, I would love to be assigned to it.

**Comment by jennydaman** [comment]
Hey @Njong392,

We don't use the "Releases" feature of Github for this repository, but you can see that we have an automatic incremental versioning scheme and automatic builds published here: https://github.com/FNNDSC/ChRIS_ui/pkgs/container/chris_ui

For more details: https://github.com/FNNDSC/ChRIS_ui/pull/508
