### ISSUE TITLE
Fix feed hint width on mobile screen

### ISSUE THREAD

**Issue by Chizycodes** [FNNDSC/ChRIS_ui#661]
![Screenshot from 2022-10-12 02-54-19](https://user-images.githubusercontent.com/53119290/195235681-4a5ed3d9-3e59-42d4-bb60-11c0951b252e.png)

**Comment by Chizycodes** [comment]
I'm working on this.

**Comment by Beyond-Logic** [comment]
@Chizycodes  I have fixed this issues already on https://github.com/FNNDSC/ChRIS_ui/pull/650

**Comment by Chizycodes** [comment]
Alright.
