### ISSUE TITLE
Page headers in the dashboard do not look the same.

### ISSUE THREAD

**Issue by Timonwa** [FNNDSC/ChRIS_ui#664]
The headers in the Library, New and Existing Analyses(1761), and Plugins, Pipelines and Compute pages look the same as below:
![chris1](https://user-images.githubusercontent.com/63044364/195259280-99229bd8-69cd-45f1-b245-e9b990cc6d0c.png)

Meanwhile, the header in the PACS Query/Retrieve page is different.
![chris2](https://user-images.githubusercontent.com/63044364/195259561-c99bf207-2e7d-4180-be78-3cb2882c1e46.png)

And the DICOM Viewer page doesn't have a header at all.
![chris5](https://user-images.githubusercontent.com/63044364/195259683-edefbd06-3aeb-419f-9d45-03b886cb7d27.png)

I am an Outreachy applicant, and I would like to work on giving all the pages the same style and if possible make the page header a reusable component.

Please assign this to me. @jennydaman @mairin

**Comment by Timonwa** [comment]
Hi @PintoGideon, can I be assigned this?

**Comment by Timonwa** [comment]
Hi @PintoGideon, I am having issues running the frontend part of the app. when I tried npm install, it was giving me errors that it couldn't install due to dependency issues. I then used npm install --legacy-peer-deps, and it finally installed, but now I can't seem to view the app on my browser. it is giving me another webpack error:
Im using windows.
```
Failed to compile.

Error: C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\src\pages\Dashboard\Dashboard.tsx: preval.macro: Command failed: npm run -s print-version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
'.' is not recognized as an internal or external command,
operable program or batch file.
 Learn more: https://www.npmjs.com/package/preval.macro
    at Array.forEach (<anonymous>)
ERROR in ./src/pages/Dashboard/Dashboard.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\src\pages\Dashboard\Dashboard.tsx: preval.macro: Command failed: npm run -s print-version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
'.' is not recognized as an internal or external command,
operable program or batch file.
 Learn more: https://www.npmjs.com/package/preval.macro
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\src\pages\Dashboard\Dashboard.tsx:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at requireFromString (C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\node_modules\require-from-string\index.js:28:4)
    at requireFromString (C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\node_modules\babel-plugin-preval\dist\helpers.js:35:47)
    at getReplacement (C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\node_modules\babel-plugin-preval\dist\helpers.js:58:18)
    at asTag (C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\node_modules\babel-plugin-preval\dist\macro.js:39:51)
    at C:\Users\Lenovo\Documents\GitHub\Outreachy\ChRIS_ui\node_modules\babel-plugin-preval\dist\macro.js:24:7
    at Array.forEach (<anonymous>)

webpack compiled with 1 error
No issues found.
```

**Comment by Timonwa** [comment]
I think the error comes from this line of code in my Dashboard.tsx. Because when I comment it out, the UI shows in my browser, but when I uncomment it again, the error appears.

I do not know what the code does so I don't know if it is wise for me to comment it out.
![Inkedice_screenshot_20221012-160638](https://user-images.githubusercontent.com/63044364/195380059-73c8cb7c-c348-4f2d-aee1-3f777ebd73e1.jpg)

**Comment by jennydaman** [comment]
@Timonwa that piece of code only works on Linux or Mac. https://github.com/FNNDSC/ChRIS_ui/issues/697

**Comment by Timonwa** [comment]
> @Timonwa that piece of code only works on Linux or Mac. #697

Oh. Ok. Thank you. I was worried I did something wrong while installing the project.
