### ISSUE TITLE
Tooltips for page header in the dashboard are not position well

### ISSUE THREAD

**Issue by Timonwa** [FNNDSC/ChRIS_ui#665]
I would like to work on this while I solve issue #664 as both are related and opened by me.

The tooltips of most of the page headers in the dashboard are positioned relative to the nav bar instead of the header it represents.
![chris1b](https://user-images.githubusercontent.com/63044364/195260416-19a0c6e8-8634-415c-b568-16eb5ce7f529.png)

On the other hand, the tooltip for the New and Existing Analyses Page is not even a tooltip.
![chris3](https://user-images.githubusercontent.com/63044364/195261039-69302728-8860-4d2e-b6cc-114c1d4f906c.png)

And the upload page doesn't have a header or tooltip at all.
![chris5](https://user-images.githubusercontent.com/63044364/195261116-1f42e3d4-7f86-43b7-9e38-0dd3f59a46de.png)

I would like to work on it. Please assign it to me. @jennydaman  @mairin

**Comment by Timonwa** [comment]
Hi @PintoGideon, can I be assigned this?

**Comment by PintoGideon** [comment]
@Timonwa  Yes !!

**Comment by Timonwa** [comment]
thank you
