### ISSUE TITLE
fixing the blank page displayed while creating a new analysis

### ISSUE THREAD

**Issue by sirichandana-v** [FNNDSC/ChRIS_ui#669]
In create a new analysis, after expanding a card in the pipelines' section, whenever we select and then deselect the card it gives a blank page.

![Screenshot (13)](https://user-images.githubusercontent.com/88175932/195388995-9c620664-a520-42ec-a212-7bd438e6bc59.png)

![Screenshot (14)](https://user-images.githubusercontent.com/88175932/195389043-2514b69f-4500-4147-a127-16dc8562295f.png)

I would like to work one this. Please assign this issue to me
@jennydaman @mairin @PintoGideon

**Comment by PintoGideon** [comment]
@sirichandana-v  Since this was a bug introduced me, I went ahead and fixed it. Could you check on https://next.chrisproject.org if this issue still exists ?

**Comment by sirichandana-v** [comment]
I checked it in the link u gave and it still does exist

**Comment by PintoGideon** [comment]
Could you check in the 20 mins and report back if it still persists? I sent out another fix.

**Comment by sirichandana-v** [comment]
yeah sure.
