### ISSUE TITLE
Image viewer is not consistent with images of various resolutions

### ISSUE THREAD

**Issue by Sandip117** [FNNDSC/ChRIS_ui#674]
When using the image viewer from the feed view, the viewer breaks while rendering images with higher resolutions

**Comment by PintoGideon** [comment]
Could you please provide screenshots since "breaks" could mean a lot of things  and also steps to reproduce this issue ? Also what are the resolutions of the images you use so that someone can test it using stock images with the same resolution.

**Comment by haszankauna** [comment]
hello @Sandip117  can you please provide a more detailed description and if possible an image that shows the error you're getting

**Comment by haszankauna** [comment]
Hello @PintoGideon  can I please be assigned to this?

**Comment by Sandip117** [comment]
![image](https://user-images.githubusercontent.com/32147904/195614554-0e2b9dbc-429a-4bc2-924e-2ccfc84b2373.png)
The image that I used above to test has a resolution 1024 X 512

It seems like the image viewer currently can only render images of resolution 256 x 256. Anything higher than that is cropped before being rendered.

**Comment by haszankauna** [comment]
@jennydaman will look into it
