### ISSUE TITLE
Plugin parameter fields allow user to enter the same parameter more than once

### ISSUE THREAD

**Issue by codeEmpress1** [FNNDSC/ChRIS_ui#683]
### To reproduce this error 
- Click on `New and Existing analyses`
- Select an analyses
- Click on `Add a Child Node`
- Select a plugin and click `next`
- Click `Add more parameters`
- Try add a parameter from the dropdown twice or more

I think the expected behaviour should be adding a parameter only once.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/47438585/195580676-27ac1e24-6fb1-4438-8ab6-4c17326ab9bc.png">

**Comment by ademolaomosanya** [comment]
hello,  Would you like to work on this issue together? :-)

**Comment by codeEmpress1** [comment]
@ademolaomosanya we can work on it together with @Quintinus98

**Comment by Quintinus98** [comment]
Okay that's nice

**Comment by Quintinus98** [comment]
Let's all communicate on Matrix

**Comment by ademolaomosanya** [comment]
okay

**Comment by jennydaman** [comment]
Hi everyone, this actually raises an interesting question. So on the command line, it is actually possible to give a value more than once. But that raises the question: if this is possible to specify in the UI:

1. what request is being sent to the backend?
2. does the backend accept the request with an argument duplicated?
3. how does the backend interpret the request?

Someone with backend skills and/or experience with HTTP/JSON requests should take a deeper look before we think about how to move forward.

**Comment by Quintinus98** [comment]
Okay @jennydaman I understand where u're looking at it from, we didn't look at that way. Thanks for the insight
