### ISSUE TITLE
pagination ui error

### ISSUE THREAD

**Issue by mightyFZeus** [FNNDSC/ChRIS_ui#686]
When there are no records, Pagination section  displays showing (0 - 12 of -1).it hsould be 0-0 0f 0. I would like to work on this

**Comment by mightyFZeus** [comment]
![Screenshot (101)](https://user-images.githubusercontent.com/67365597/195600738-f5ca4920-0e2d-4793-82f4-8c800150b640.png)

**Comment by mightyFZeus** [comment]
Ohhh yes we can

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/fnndsc/issues/76
