### ISSUE TITLE
error message is not visible upon login with invalid credentials

### ISSUE THREAD

**Issue by nanfuka** [FNNDSC/ChRIS_ui#690]
![Screenshot from 2022-10-17 07-25-23](https://user-images.githubusercontent.com/29108523/196089512-9858cecb-6c78-4bcb-9cdf-ab668af4033d.png)
go to the Chris ui login page, enter invalid username and password, click save. the error message will pop up at the top. The error message is not not visible since its the same color as the rest of the text of the page. it should have the resemblance of the rest of the error messages in the application. Also the login button should respond upon being clicked.

**Comment by Timonwa** [comment]
Hi, @nanfuka can you add a screenshot of the error? and if you are already working on this, can you please indicate?

**Comment by thessakranendonk** [comment]
Hi @nanfuka! I'm an Outreachy participant and I looked at the bug. I think I figured out what's causing this to happen. By trying to log in and looking at the issue I also noticed the login button doesn't respond to the enter press. I would like to add that functionality too if that's okay.

**Comment by nanfuka** [comment]
If you look closely at the image above, you will notice an error message at the top, but its not easy to tell whether this is an error message since it differs from other error messages. the issue is it should look like  the other error messages in the application. also when you click on the login button, you might not know that you clicked on it since its appearance remains constant

**Comment by nanfuka** [comment]
may be someone else can take it on. i have not assigned it to myself.

**Comment by AndroGenius-codes** [comment]
Hello there just seeing this. I did a bit of fix for this issue at issue 
#708

**Comment by thessakranendonk** [comment]
Hi sorry I just noticed we both worked on this. I looked at your code and it's interesting to see how we both approached this issue so differently haha. I added the functionality to be able to login by enter press and stored the error messages in an enum.

**Comment by AndroGenius-codes** [comment]
> Hi sorry I just noticed we both worked on this. I looked at your code and it's interesting to see how we both approached this issue so differently haha. I added the functionality to be able to login by enter press and stored the error messages in an enum.

lol oh oh. the more the merrier your fix looks great

**Comment by jennydaman** [comment]
I'm seeing several PRs related to this:

- https://github.com/FNNDSC/ChRIS_ui/pull/702
- https://github.com/FNNDSC/ChRIS_ui/pull/708
- https://github.com/FNNDSC/ChRIS_ui/pull/710

I have skimmed them all and left some comments. I am challenging you all to think of better solutions. In the end, only one (or none) of these PR can get merged, though I will consider all of these attempts in your final Outreachy applications.
