### ISSUE TITLE
Sef-updating build string does not work on Windows

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#697]
It's useful to see in the "Overview" tab when ChRIS_ui was last updated, so we use a bash script to print git information and the date at build-time. The script output gets rendered into the JSX. https://github.com/FNNDSC/ChRIS_ui/pull/508

This script doesn't work on Windows. https://github.com/FNNDSC/ChRIS_ui/issues/664#issuecomment-1276339800 Even though we don't intend to support Windows as a development environment, it is more elegant if we can achieve a pure node.js project for cross-platform compatibility and perhaps to better benefit from static code analysis tools.

For the most part, I think `print_version.sh` can be translated from bash to pure node.js, and using cross-platform commands such as `git` and `npm` only.

**Comment by Quintinus98** [comment]
@jennydaman I would like to work on this issue. As discussed in the meeting, I'd go ahead and start, since I'm the first to comment on the issue

**Comment by ciradu2204** [comment]
@jennydaman, can I collaborate with @Quintinus98?

**Comment by Quintinus98** [comment]
I'd like to collaborate with you @ciradu2204
