### ISSUE TITLE
Enforce strict code style to prevent merge conflicts

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#698]
Currently, ChRIS_ui uses a permissive canned eslint configuration.

https://github.com/FNNDSC/ChRIS_ui/blob/49193ea8b5a0798c0004ff56ee56a0604d72c706/package.json#L67

The IDE auto-formatters of many contributors will do things like add semicolons, change quotes from single to double, ... making PR diffs hard to read and causing merge conflicts between branches.

This is a feature request for us to use a strict linter and a Github Actions workflow to check code style. Merging of PRs should only be allowed if and only if the code style check passes.

We can steal the eslint configuration from ChRIS_store_ui. See https://github.com/FNNDSC/ChRIS_store_ui/issues/168 and its linked PR https://github.com/FNNDSC/ChRIS_store_ui/pull/229

**Comment by nanfuka** [comment]
@Timonwa can I collaborate with you on this on this issues. i have some experience there.

**Comment by Timonwa** [comment]
No problem @nanfuka. I made a comment on the pull request. Let me tag you on it.
