### ISSUE TITLE
Request inefficiency

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#701]
Same HTTP GET request is made from the frontend to the backend during initial load of a page, e.g. the feed view page. Performance can be optimized by identifying where these duplicate requests are being made and reusing existing variables, or implementing a HTTP call cache (maybe use service worker proxy?).

![screenshot](https://user-images.githubusercontent.com/20404439/195808173-14970305-b776-4ad3-b0cd-9f23f241d1c2.png)

**Comment by mightyFZeus** [comment]
I will work on this @jennydaman

**Comment by mightyFZeus** [comment]
If you want to collaborate on this, do well to reach out please

**Comment by Jem256** [comment]
Hey @mightyFZeus can I collaborate with you on this issue?

**Comment by mightyFZeus** [comment]
Yes you can....send me a Dm on matrix @olabisi so we can set up a meeting.

**Comment by Headon1729** [comment]
Hey @Jem256, @mightyFZeus 
Are you guys still working on the issue because otherwise I would like to work this issue as well ?

**Comment by mightyFZeus** [comment]
@Headon1729 hi, yes you can. @Jem256 stopped working on it with me. Send me a text on matrix @olabisi
