### ISSUE TITLE
Number of feeds in header displayed as [object Object]

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#713]
<img width="1375" alt="Screen Shot 2022-10-18 at 4 51 59 PM" src="https://user-images.githubusercontent.com/20404439/196542569-60959d38-21a1-440b-a5d0-f6a290661d23.png">

**Comment by ademolaomosanya** [comment]
i would love to work on this @jennydaman

**Comment by ademolaomosanya** [comment]
okay @dipanshuraz
