### ISSUE TITLE
Disable "Add a Child Node" button and edit title functionality if logged in user does not own the feed

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#714]
<img width="1375" alt="Screen Shot 2022-10-18 at 4 54 05 PM" src="https://user-images.githubusercontent.com/20404439/196542756-449374b5-1184-4e91-b67a-01f3f3ebf05f.png">

Logged in as the user "chris" but feed owner is "Rudolph". Cannot edit feeds owned by another user, so any edit operations should be disabled/greyed out.

**Comment by ademolaomosanya** [comment]
i would love to work on this @jennydaman

**Comment by JulianaSau** [comment]
I'd also like to work on this issue

**Comment by ademolaomosanya** [comment]
we can work together on it @JulianaSau

**Comment by JulianaSau** [comment]
That would be great.

**Comment by Headon1729** [comment]
@JulianaSau @ademolaomosanya If you are not working on this issue, I would love to work on it too

**Comment by JulianaSau** [comment]
Hey, we are still working on the issue

**Comment by ademolaomosanya** [comment]
@ciradu2204 yes would you like to join us?

**Comment by ciradu2204** [comment]
yeah, that's okay.
