### ISSUE TITLE
Add a view button on the create feed finish step

### ISSUE THREAD

**Issue by ciradu2204** [FNNDSC/ChRIS_ui#729]
After creating a feed, on the finish step, there is a cancel button which does not have much significance. Currently, clicking the cancel button directs the user to the feeds list.  The idea we have ( I and @Quintinus98) is to replace the cancel button with a view button which directs the user to view that specific field they just created. 

Screenshot: 
<img width="1223" alt="Screen Shot 2022-10-25 at 14 07 13" src="https://user-images.githubusercontent.com/37863089/197769004-88f43863-2a40-4212-8317-7bc0f0c8b502.png">

How to produce the issue: 
1. Login and click on the new and existing tab on the menu list
2. Click on create analysis button and follow the normal process of creating a feed
3. On the finish step after creating a feed, you will see the cancel button.

**Comment by ciradu2204** [comment]
@PintoGideon @jennydaman, please let us know if the feature is helpful. Thanks

**Comment by Quintinus98** [comment]
Nicely done @ciradu2204.
Once this issue gets approved let's work on it together

@jennydaman @PintoGideon @mairin what do you think. Thank you
