### ISSUE TITLE
Add node ui drop down. 

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_ui#74]
It looks like the Drop Down in the UI for "All plugins" only shows the first page of plugins returned by the backend.

**Comment by PintoGideon** [comment]
@jcaianirh  Working on this.

**Comment by PintoGideon** [comment]
![Issues_74](https://user-images.githubusercontent.com/15992276/74454857-81315480-4e52-11ea-9d61-cf2098ab304c.png)
