### ISSUE TITLE
Breadcrumbs for the tabs in the Library section do no have a uniform style.

### ISSUE THREAD

**Issue by Timonwa** [FNNDSC/ChRIS_ui#749]
The Library section has three tabs: Uploads, Completed Analysis and Services. As you select and open folders in any of the tabs, a breadcrumb shows you the steps of the folders you have opened to get to a particular file, and you can click on any of them to go back to that particular folder. But the logic for this breadcrumb is not the same for the three tabs.

The **Uploads** tab on the initial page load starts with the logged-in user's name, which is not clickable and the tab's name (Uploads). It then shows the name of whatever folder you click subsequently.

The **Completed Analysis** tab on the initial page load starts with a `/`.  Then when you click on a folder, it shows **root** as the tab's name. It is also colour black instead of blue like the rest of the clickable links. The breadcrumbs are also on a different line from **Root**, and the subsequent folders do not have any icon beside them except for the currently active folder.

The **Services** tab on the initial page load starts with the tab's name in Uppercase and a multicoloured icon before showing the name of whatever folder you click subsequently. 

![image1](https://user-images.githubusercontent.com/63044364/201664612-255e21e7-089f-4944-becc-00f5c3c2a2e5.png)
![image2](https://user-images.githubusercontent.com/63044364/201664617-a16826d4-66b1-4fd4-b34c-73dd78ea5d67.png)
![image3](https://user-images.githubusercontent.com/63044364/201664621-7547b8b9-12b2-4506-b51e-48e252bcc1d8.png)

My proposed changes are that the three breadcrumbs start with the name of the tab they represent, followed by the name of the folders the user clicks. The tab name in the breadcrumb should also have its first letter capitalized only, with the colour blue. Their icons should also be coloured blue and bd the same folder icon. And all folders should have an icon beside them.

**Comment by Timonwa** [comment]
I would like to work on this. @jennydaman @PintoGideon

**Comment by PintoGideon** [comment]
Sounds good @Timonwa

**Comment by jennydaman** [comment]
I agree that the `root` button from the "Completed Analysis" tab sticks out and should be changed.

"Uploads" is browsable from `<username>/uploads` whereas "Completed Analysis" is browsable from "root" — could the reason be to support shared feeds? For instance, user can't see other user's uploaded files, but if a feed is shared with you, then you should be able to browse that feed's files under `<other_username>/feed_N`

**Comment by PintoGideon** [comment]
Yes, Completed Analysis is browsable from root to support shared feeds.

**Comment by Timonwa** [comment]
Would you like the `root` button to bear the name root still then, or would you like it to be changed to something else?
