### ISSUE TITLE
Bug: plugin select component displaying duplicates

### ISSUE THREAD

**Issue by ciradu2204** [FNNDSC/ChRIS_ui#778]
The plugin select component displays duplicate plugins. Instead, the plugin selection should "group" plugins with the same name, then the option to choose which version should appear in a dropdown (either on the same page or the next). 

The suggested way from @jennydaman  to avoid duplicates: 
The backend should call "plugin meta" instead of "plugins": "plugin meta" are unique by name, and "plugins" are unique by (name, and version). "plugin meta" correspond to one or more plugins with the same name but different versions. so the plugin selection screen should show a list of plugin meta, not plugins.

**Comment by Quintinus98** [comment]
Hello @PintoGideon could you assign me this issue.

**Comment by Quintinus98** [comment]
Thanks
