### ISSUE TITLE
Ugly hash URL appears when clicking on filebrowser breadcrumb in feed view

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#784]
known affected version 3ebef7788ec0ac9f9cb4cf10129ff8f6e368767a

![image](https://user-images.githubusercontent.com/20404439/211626467-e7fa79b0-da89-4ff2-b5d8-81341f708947.png)

If you click on "subjects" in the breadcrumbs, the URL changes from `http://localhost:3000/feeds/1` to `http://localhost:3000/feeds/1#`

**Comment by betty-alagwu** [comment]
Hello @jennydaman i've been able to reproduce this bug, i'll love to work on it

**Comment by betty-alagwu** [comment]
Thank you, on it
