### ISSUE TITLE
Streamline upload process in Create New Analysis workflow

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ui#800]
(From [12 Jan 2023 ChRIS weekly status meeting](https://matrix.to/#/!JIamxaDyfGKOnxIaDN:fedora.im/$BotRHv6tYPSqK_y2yimTlSHYzjLPGaFeVZ-qPz8563U?via=fedora.im&via=matrix.org)):

![Screenshot from 2023-01-12 10-20-05](https://user-images.githubusercontent.com/799683/212734921-fee13709-3208-47e2-9d78-6d8a5f78a4aa.png)

On the far right, clicking on "Upload New Data" brings you to a sub-screen with an upload form. When you upload files/folders through the form, that subscreen gives you a list of files (that you can edit, by removing files from the selection with an X icon). You then can click next to continue with analysis set up.

The proposal here is when you click on "Upload New Data" on the screen above, you'll immediately get a "Browse Files..." upload dialog. Make your selection in the dialog, and exit the upload dialog, *then* you'll be brought to the subscreen with the list of files. From there you can remove files from the selection or add additional ones.

So the suggestion here isn't to completely remove the subscreen, but let the user go right to uploading files immediately, then bring up the subscreen as a confirmation, and let them hit "Next" from the subscreen to continue through the workflow. This should streamline the experience and require less clicks / etc.

**Comment by jennydaman** [comment]
A related comment: the progress bar should increment after each file upload (the current behavior is that the progress bar is frozen until all files are uploaded)
