### ISSUE TITLE
Delete node bugs

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#816]
![image](https://user-images.githubusercontent.com/20404439/215568857-de586bc0-2b78-4e89-9f79-b4b155937946.png)

I tried to delete two nodes, and the UI crashed.

**Comment by PintoGideon** [comment]
Hey @jennydaman , Did you try to delete active (waiting, running) nodes ?

**Comment by jennydaman** [comment]
running
