### ISSUE TITLE
Analysis Type selection while creating new analysis 

### ISSUE THREAD

**Issue by itsgurmannatsohal** [FNNDSC/ChRIS_ui#830]
![image](https://user-images.githubusercontent.com/95538438/217520882-dd722465-d20b-4e4e-b246-bb9ebb7945de.png)

On creating new analysis, the drag and drop option gets disabled once we click on it, even if the files were not uploaded. The disabled button remains clickable and stays that way unless some other option is selected once.

**Comment by itsgurmannatsohal** [comment]
@jennydaman Kindly assign me this issue. I'd like to work on it.

**Comment by PintoGideon** [comment]
This issue is actively being worked on by someone else.

**Comment by PintoGideon** [comment]
Thanks for reporting the issue. Feel free to look into other issues and work on something that catches your attention.

**Comment by itsgurmannatsohal** [comment]
Sorry, is this a duplicate issue? Because this one hasn't been claimed by anyone yet

**Comment by PintoGideon** [comment]
It's been worked upon by @ciradu2204 .
