### ISSUE TITLE
Feed note appears in "Times New Roman" font

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#862]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/20404439/223762979-f80b22cb-7f94-4239-adcd-5221661c2288.png">

Expected font to be the same as it is everywhere else in ChRIS_ui

**Comment by DevBramz** [comment]
@jennydaman I am an outreachy applicant and would like to work on this issue as part of my contributions

**Comment by PintoGideon** [comment]
@DevBramz  I fixed it. If possible, could you find other bugs in the code and list them down to tackle. I would also use https://nightly.chrisproject.org to stay current.

**Comment by DevBramz** [comment]
Ooh okay thanks for the headsup
