### ISSUE TITLE
Terminal output disappears when it is updated

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#863]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/20404439/223764339-629bee9d-49be-43c0-9aa6-d23852c9d4ba.png">

The terminal output reappears when you scroll in the box:

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/20404439/223764522-db076e15-6233-426e-8b7c-3037ac156271.png">

Expected behavior is for the terminal text to always be visible, and for the terminal box to scroll itself down as new lines appear.

**Comment by DevBramz** [comment]
@jennydaman  can you assign me this issue would love to work on it?
