### ISSUE TITLE
Delete Feed modal is not dismissed when confirm button clicked

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#884]
### Steps to Reproduce

1. Create a feed
2. Select the feed
3. Click the delete icon
4. Click "Confirm"

![image](https://user-images.githubusercontent.com/20404439/227121665-c2c75df8-5257-45d8-92f0-dfe8b50d5a49.png)

Expected: feedback, e.g. delete successful, or modal closes itself

Actual: modal stays there

**Comment by Prakashh21** [comment]
should it close in all the other cases aswell ..?  i.e. share , download , merge ..?
