### ISSUE TITLE
Cursor cannot be moved using left right arrow keys in "Add a New Node" parameter value input box

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#921]
![image](https://user-images.githubusercontent.com/20404439/235745033-3bfeaea1-7350-4667-8359-a6be9012db11.png)

**Comment by ciradu2204** [comment]
Hi @jennydaman , 

I can't seem to replicate this issue. Which plugin did you use? 

https://user-images.githubusercontent.com/37863089/236256732-2ffb764b-b65a-4125-ab59-71e0877b456e.mov

**Comment by jennydaman** [comment]
You're right, I'm unable to reproduce it either on nightly.

I'll close this (and reopen if I notice it again)
