### ISSUE TITLE
Regression: unable to rotate feed tree

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#942]
![image](https://github.com/FNNDSC/ChRIS_ui/assets/20404439/5bf94d06-aae0-4ef9-95c7-5659bd66be85)

Clicking on the highlighted button does nothing.

**Comment by PintoGideon** [comment]
This issue was addressed in the latest pull request. However, we need to ensure that the tree is centered on the screen when the layout is horizontal. We'll track this issue in a separate pull request
