### ISSUE TITLE
Goes to previous page instead of homepage after successful login.

### ISSUE THREAD

**Issue by chhsiao1981** [FNNDSC/ChRIS_ui#979]
Found that the behavior of successful login changed from homepage to previous page.

This is extremely confusing when the users directly goes to

http://chris-next.tch.harvard.edu/login

https://github.com/FNNDSC/ChRIS_ui/commit/da7a244a85a20edb82ca4f00e8b3f17ab965a5a3

**Comment by PintoGideon** [comment]
Fixed
